Repository Team-WSS/WSS-Android, pull requests merged in 2024-11, with the labels that each got.

#413 feat: 유저 취향이 존재하지 않을시 "취향이 존재하지 않아요" 화면 구현
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryViewModel.kt
  app/src/main/res/layout/fragment_other_user_library.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#414 feat: 내 활동/ 다른유저 활동 존재하지 않을 시 화면 구현
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
  app/src/main/res/layout/fragment_my_activity.xml
  app/src/main/res/layout/fragment_other_user_activity.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#415 feat: 보관함 null 화면 구현
  app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageItemAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageViewPagerViewHolder.kt
  app/src/main/res/layout/activity_storage.xml
  app/src/main/res/layout/item_storage.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#420 feat: 설정 뷰 3차 QA 반영
  app/src/main/res/drawable/ic_with_draw_watched.xml
  app/src/main/res/drawable/ic_withdraw_watched.xml
  app/src/main/res/layout/activity_account_info.xml
  app/src/main/res/layout/activity_withdraw_first.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#412 feat: 활동 관련 뷰 더보기 팝업메뉴 구현
  app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/model/ActivityDetailUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/MyActivityUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/model/OtherUserActivityUiState.kt
  app/src/main/res/layout/item_my_activity.xml
  app/src/main/res/layout/menu_my_activity_popup.xml
  app/src/main/res/layout/menu_other_user_activity_popup.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#416 feat: 다른유저 비공개 화면 구현
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageActivity.kt
  app/src/main/res/drawable-xhdpi/img_other_user_page_no_public.png
  app/src/main/res/drawable-xxhdpi/img_other_user_page_no_public.png
  app/src/main/res/drawable-xxxhdpi/img_other_user_page_no_public.png
  app/src/main/res/layout/activity_other_user_page.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#422 feat: 내 서재/ 다른유저 서재에 따른 보관함 조회 분기처리 구현
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageViewModel.kt
Labels: 🍯 [FEAT], 👛 황후 연진

#421 feat: 소셜로그인 및 토큰 관리 로직 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/WebsosoApp.kt
  app/src/main/java/com/teamwss/websoso/data/authenticator/WebsosoAuthenticator.kt
  app/src/main/java/com/teamwss/websoso/data/di/ApiModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/OAuthModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/RepositoryModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/SecureStorageModule.kt
  app/src/main/java/com/teamwss/websoso/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/KakaoTokenMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/LoginMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/LoginEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/OAuthToken.kt
  app/src/main/java/com/teamwss/websoso/data/qualifier/Auth.kt
  app/src/main/java/com/teamwss/websoso/data/qualifier/Interceptor.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/AuthApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/KakaoAuthService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/OAuthService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/LogoutRequestDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/TokenReissueRequestDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/WithdrawRequestDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/KakaoLoginResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/KakaoTokenReissueResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/AuthRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/CheckNicknameValidityUseCase.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/ValidateNicknameUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/accountInfo/AccountInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/accountInfo/LogoutDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/login/LoginActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/login/LoginViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/login/model/LoginUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/model/MainUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/splash/SplashActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/splash/SplashViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/second/WithdrawSecondActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/second/WithdrawSecondViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_onboarding_second.xml
  app/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#423 feat: 마이페이지/다른유저페이지 관련 에러대응 및 로딩화면 구현
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/model/MyLibraryUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/BlockUserDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/model/OtherUserPageUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/model/OtherUserLibraryUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageViewModel.kt
  app/src/main/res/layout/activity_activity_detail.xml
  app/src/main/res/layout/activity_other_user_page.xml
  app/src/main/res/layout/activity_storage.xml
  app/src/main/res/layout/fragment_my_activity.xml
  app/src/main/res/layout/fragment_my_library.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_other_user_activity.xml
  app/src/main/res/layout/fragment_other_user_library.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#426 feat: 피드 데이터 변경 즉시 반영 구현
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/ActivitiesModel.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/ActivityMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityViewModel.kt
Labels: 🍯 [FEAT], 👛 황후 연진

#428 feat: 탈퇴한 회원 프로필 진입 차단 구현
  app/src/main/java/com/teamwss/websoso/common/ui/model/ResultFrom.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/second/WithdrawSecondViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#432 feat: 장르취향 펼치기 아이콘 터치영역 증가, 내 활동 활동기록 더보기 등장 로직 수정
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/setting/SettingActivity.kt
  app/src/main/res/layout/fragment_my_activity.xml
  app/src/main/res/layout/fragment_my_library.xml
  app/src/main/res/values/deepLinks.xml
Labels: 🍯 [FEAT], ♻️ [REFACTOR], 🗡️ 대장군 재원

#435 feat: 댓글 상태 분기처리
  app/src/main/java/com/teamwss/websoso/data/mapper/FeedMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/CommentEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/CommentResponseDto.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailCommentViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/CommentModel.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/FeedMapper.kt
  app/src/main/res/layout/item_feed_detail_comment.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#436 feat: 뒤로가기 두 번 클릭시 종료
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#438 fix: 피드 추가 로딩 수정
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedViewModel.kt
Labels: 🔨 [FIX], 🔮 법사 준서

#429 feat: 활동 디테일 무한스크롤 구현
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/model/ActivityDetailUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/model/ActivityType.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/MyActivityUiState.kt
Labels: 🍯 [FEAT], 👛 황후 연진

#434 feat: 작품상세 뷰 3차 QA 대응
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/AvatarMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/menu_novel_detail_popup.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#442 fix: 프로필 편집 후 내 활동에 반영되지 않는 문제
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
Labels: 🏹 궁사 명지, 🔨 [FIX]

#444 feat: 로컬에 유저 성별 저장
  app/src/main/java/com/teamwss/websoso/common/ui/model/Gender.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeUserRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/ChangeUserInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/model/ChangeUserInfoUiState.kt
Labels: 🍯 [FEAT], 🏹 궁사 명지

#441 feat: 보관함 무한스크롤 구현
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageItemAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageViewPagerViewHolder.kt
Labels: 🍯 [FEAT], 👛 황후 연진

#440 refactor: 피드 작성하기 뷰 3차 QA 대응
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/model/CreateFeedCategory.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/res/layout/activity_create_feed.xml
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈

#446 fix: 내 활동/ 내 서재 전체 높이 설정
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
Labels: 🍯 [FEAT], 👛 황후 연진

#447 refactor: 4차 QA 대응
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/data/di/ApiModule.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/ChangeUserInfoActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/ChangeUserInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreDialogBottomSheet.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/FeedDetailModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/FeedDetailUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
  app/src/main/res/layout/item_feed_detail_header.xml
  app/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈

#452 feat: 작품상세 뷰 5차 QA 반영
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#454 feat: 상세 탐색 5차 QA
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#460 feat: 보관함 무한스크롤 제거
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageItemAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageViewPagerViewHolder.kt
Labels: 🍯 [FEAT], 👛 황후 연진

#462 feat: 활동 디테일 무한스크롤 제거
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/model/ActivityType.kt
Labels: 🍯 [FEAT], 👛 황후 연진

#463 refactor: 4차 QA 반영
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryViewModel.kt
  app/src/main/res/layout/activity_other_user_page.xml
  app/src/main/res/layout/fragment_my_library.xml
  app/src/main/res/layout/fragment_other_user_library.xml
Labels: ♻️ [REFACTOR], 👛 황후 연진

#459 refactor: 작품피드 뷰 본인 프로필 이동 잠금
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
Labels: ♻️ [REFACTOR], 🔮 법사 준서

#461 refactor: 5차 QA 반영
  app/src/main/java/com/teamwss/websoso/common/ui/model/ResultFrom.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/FeedDetailUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedItemClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedViewModel.kt
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈

#470 fix: 작품평가 뷰 키워드 오류 해결
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelRatingMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiModel.kt
  app/src/main/res/drawable/ic_novel_detail_quit.xml
  app/src/main/res/drawable/ic_novel_detail_quit_deselected.xml
  app/src/main/res/drawable/ic_novel_detail_quit_selected.xml
  app/src/main/res/drawable/ic_novel_detail_quit_selector.xml
  app/src/main/res/drawable/ic_novel_detail_watched.xml
  app/src/main/res/drawable/ic_novel_detail_watched_deselected.xml
  app/src/main/res/drawable/ic_novel_detail_watched_selected.xml
  app/src/main/res/drawable/ic_novel_detail_watched_selector.xml
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/item_common_keyword.xml
Labels: 🔨 [FIX], 🔮 법사 준서

#474 feat: 마이페이지 5차 QA 반영
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/ActivitiesModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
  app/src/main/res/layout/activity_other_user_page.xml
  app/src/main/res/layout/fragment_other_user_activity.xml
  app/src/main/res/layout/fragment_other_user_library.xml
Labels: ♻️ [REFACTOR], 👛 황후 연진

#475 feat: 릴리즈 직전 QA 반영
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedSearchNovelBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/EditFeedModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/notice/NoticeActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_activity.xml
  app/src/main/res/layout/item_feed_detail_comment.xml
  app/src/main/res/values/deepLinks.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서
