Repository Team-WSS/WSS-Android, pull requests merged in 2024-01, with the labels that each got.

#9 build : 폴더 구조, 폴더 이름, 폴더 이름 오타수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/data/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/gitkeep
  app/src/main/java/com/teamwss/websoso/data/model/gitkeep
  app/src/main/java/com/teamwss/websoso/data/repository/gitkeep
  app/src/main/java/com/teamwss/websoso/ui/keyword/KeywordActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
  app/src/main/java/com/teamwss/websoso/util/gitkeep
  app/src/main/res/layout/activity_keyword.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_memo_write.xml
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/activity_post_novel.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_home.xml
Labels: 🚧 [BUILD], 🗡️ 대장군 재원

#10 feat: 바텀네비게이션 design system 적용, 변경된 디자인 적용
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/res/color/selc_bottom_nav_item.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_bottom_nav.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#11 feat: 1차 과제 리드미 작성
  README.md
  thumbnail.png
Labels: 🍯 [FEAT], 🏹 궁사 명지

#17 feat: 타이포 그래피 lineHeight 값 수정 및 리드미 수정
  README.md
  app/src/main/res/values/typography.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#18 feat: record view 구현
  app/build.gradle.kts
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/model/Memo.kt
  app/src/main/res/drawable/bg_primary50_corner_12dp.xml
  app/src/main/res/layout/fragment_recode.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/item_memo.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#24 feat: search view 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/search/model/SearchResult.kt
  app/src/main/res/drawable/bg_gray50_radius_12dp.xml
  app/src/main/res/drawable/bg_stroke_gray70_2dp_radius_12dp.xml
  app/src/main/res/drawable/ic_search_cancel.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_search_novel.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#25 feat: post view MVVM 패턴 적용
  app/build.gradle.kts
  app/src/main/java/com/teamwss/websoso/data/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/WssService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/PostNovelRequest.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/EditNovelResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/PlatformGetResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/PostNovelResponse.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/DatePickerDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNavigateLeftDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/postNovelDialog/DatePickerDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/postNovelDialog/ExitPopupDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/postNovelDialog/PostSuccessDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/postNovelViewModel/PostNovelViewModel.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdpater.kt
  app/src/main/res/drawable-xhdpi/img_loading_thumbnail.png
  app/src/main/res/drawable-xxhdpi/img_loading_thumbnail.png
  app/src/main/res/drawable/ic_status_drop.xml
  app/src/main/res/drawable/ic_status_finish.xml
  app/src/main/res/drawable/ic_status_wish.xml
  app/src/main/res/drawable/img_loading_thumbnail.png
  app/src/main/res/drawable/shape_post_navigate_to_memo.xml
  app/src/main/res/layout/activity_post_novel.xml
  app/src/main/res/layout/dialog_date_picker.xml
  app/src/main/res/layout/dialog_post_exit.xml
  app/src/main/res/layout/dialog_post_success.xml
  app/src/main/res/raw/lottie_post_success.json
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#31 fix: 이미지 로드 오류 수정
  app/src/main/java/com/teamwss/websoso/data/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/AuthService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/AvatarService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/MemoService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/NovelService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/UserNovelService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/gitkeep
  app/src/main/java/com/teamwss/websoso/util/BindingAdpater.kt
Labels: 🔨 [FIX], 🔮 법사 준서

#33 fix: 바인딩 어댑터 빌드 오류 수정
  app/src/main/java/com/teamwss/websoso/util/BindingAdpater.kt
  app/src/main/res/layout/activity_post_novel.xml
Labels: 🔨 [FIX], 🔮 법사 준서

#27 feat: NovelDetail 뷰 및 MemoWrite 뷰 구현
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelMemoInfoResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelMemoResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/gitkeep
  app/src/main/java/com/teamwss/websoso/ui/memoWrite/DialogMemoCancel.kt
  app/src/main/java/com/teamwss/websoso/ui/memoWrite/DialogMemoDelete.kt
  app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelMemoViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/adapter/NovelDetailMemoAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/adapter/NovelDetailViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/DialogNovelDelete.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/NovelMemoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
  app/src/main/res/drawable/bg_gray50_radius_8dp.xml
  app/src/main/res/drawable/bg_primary200_radius_8dp.xml
  app/src/main/res/drawable/bg_primary50_radius_20dp.xml
  app/src/main/res/drawable/bg_stroke_primary100_20.xml
  app/src/main/res/drawable/bg_white_radius_12dp.xml
  app/src/main/res/drawable/ic_add_memo.xml
  app/src/main/res/drawable/ic_calendar_black.xml
  app/src/main/res/drawable/ic_warning_circle.xml
  app/src/main/res/drawable/img.jpg
  app/src/main/res/layout/activity_memo_write.xml
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/dialog_memo_cancel.xml
  app/src/main/res/layout/dialog_memo_delete.xml
  app/src/main/res/layout/dialog_novel_delete.xml
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/layout/fragment_novel_memo.xml
  app/src/main/res/layout/item_custom_popup_drop_down.xml
  app/src/main/res/layout/item_memo.xml
  app/src/main/res/layout/item_novel_memo.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/shape.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#37 fix: 마이페이지 에러 수정
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
Labels: 🔨 [FIX], 👛 황후 연진

#35 feat: library view 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/App.kt
  app/src/main/java/com/teamwss/websoso/data/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/data/authInterceptor/AuthInterceptor.kt
  app/src/main/java/com/teamwss/websoso/data/local/WebsosoLocalStorage.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/gitkeep
  app/src/main/java/com/teamwss/websoso/data/mapper/userNovelsMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/LibraryUserNovelEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/gitkeep
  app/src/main/java/com/teamwss/websoso/data/remote/request/LoginRequest.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/UserNovelsLibraryRequest.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/gitkeep
  app/src/main/java/com/teamwss/websoso/data/remote/response/LoginResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserNovelsLibraryResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/AuthService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/UserNovelService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/gitkeep
  app/src/main/java/com/teamwss/websoso/data/repository/AuthRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserNovelsRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/gitkeep
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/LibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/adapter/LibraryItemAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/adapter/LibraryItemViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/adapter/LibraryViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/adapter/LibraryViewPagerViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/model/ReadState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/model/SortType.kt
  app/src/main/res/drawable/ic_star_empty.xml
  app/src/main/res/drawable/ic_star_full.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_library.xml
  app/src/main/res/layout/item_library_novel.xml
  app/src/main/res/layout/item_library_view_pager.xml
  app/src/main/res/menu/overflow_home_menu.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#41 feat: record api 구현
  app/src/main/java/com/teamwss/websoso/data/remote/response/RecordMemoResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/RecordResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/MemoService.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/model/Memo.kt
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/item_memo.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#44 feat: search view api 연결
  app/src/main/java/com/teamwss/websoso/data/remote/response/SearchNovelsResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/NovelService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/UserNovelService.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/search/searchViewModel/SearchViewModel.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdpater.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_search_novel.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#45 feat: 메모 작성 정보 조회 뷰 api 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/data/remote/request/MemoWriteRequest.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/MemoPlainResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/MemoWriteResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelMemoInfoResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelMemoResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelPlatformInfoResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/MemoService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/UserNovelService.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/memoPlain/DialogMemoDelete.kt
  app/src/main/java/com/teamwss/websoso/ui/memoPlain/MemoPlainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/memoPlain/MemoPlainViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelMemoViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/adapter/NovelDetailMemoAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/DialogNovelDelete.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/NovelMemoFragment.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdpater.kt
  app/src/main/java/com/teamwss/websoso/util/CustomSnackBar.kt
  app/src/main/res/drawable/bg_gray_toast_radius_4dp.xml
  app/src/main/res/layout/activity_memo_plain.xml
  app/src/main/res/layout/activity_memo_write.xml
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/custom_snack_bar.xml
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/layout/fragment_novel_memo.xml
  app/src/main/res/layout/item_novel_memo.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#49 feat: record 메모 클릭리스너 구현
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordViewModel.kt
Labels: 🍯 [FEAT], 👛 황후 연진

#46 feat: API 명세서 수정에 따른 post view 반영
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelEditResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelPostResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserNovelPostResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/NovelService.kt
  app/src/main/java/com/teamwss/websoso/ui/common/model/Platforms.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/dialog/DatePickerDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/dialog/ExitPopupDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/dialog/PostSuccessDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/model/PostNovelInfoModel.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/search/searchViewModel/SearchViewModel.kt
  app/src/main/res/layout/activity_post_novel.xml
  app/src/main/res/layout/dialog_date_picker.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#50 feat: mypage api 연결 및 데이터 바인딩 적용
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/App.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/AvatarResponseMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/UserInfoMyPageResponseMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/AvatarEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/RepresentiveAvatarEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserInfoMyPageEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/NicknamePatchRequest.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/RepresentativeAvatarPatchRequest.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/AvatarHomeResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/AvatarResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserAvatarResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserInfoMyPageResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/AuthService.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/AvatarService.kt
  app/src/main/java/com/teamwss/websoso/data/repository/AuthRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/AvatarRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/LibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/AvatarDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeNickName/ChangeNicknameActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeNickName/ChangeNicknameViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/checkUserInfo/CheckUserInfoActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/model/Avatar.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/model/Memo.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdpater.kt
  app/src/main/java/com/teamwss/websoso/util/LottieImageUtil.kt
  app/src/main/res/drawable/bg_stroke_primary100_20.xml
  app/src/main/res/layout/activity_change_nickname.xml
  app/src/main/res/layout/activity_check_user_info.xml
  app/src/main/res/layout/dialog_avatar.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_avatar.xml
  app/src/main/res/raw/lottie_regressor_1.json
  app/src/main/res/raw/lottie_regressor_2.json
  app/src/main/res/raw/lottie_sosocat_1.json
  app/src/main/res/raw/lottie_sosocat_2.json
  app/src/main/res/raw/lottie_villainess_1.json
  app/src/main/res/raw/lottie_villainess_2.json
Labels: 🍯 [FEAT], 🗡️ 대장군 재원, 👛 황후 연진

#53 feat: post view에서 서버 전송시 분기처리 추가
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
  app/src/main/res/layout/activity_post_novel.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#55 feat: QA전 디테일 추가
  app/src/main/java/com/teamwss/websoso/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/adapter/LibraryViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/adapter/LibraryViewPagerViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/AvatarDialogFragment.kt
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#62 refactor: search view QA 대응
  app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/search/searchViewModel/SearchViewModel.kt
  app/src/main/res/drawable/shape_search_cursor.xml
  app/src/main/res/layout/activity_search.xml
Labels: ♻️ [REFACTOR], 🔮 법사 준서

#63 refactor: record ui 수정
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], 👛 황후 연진

#69 refactor: library QA 대응
  app/src/main/java/com/teamwss/websoso/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/library/adapter/LibraryViewPagerViewHolder.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdpater.kt
  app/src/main/res/layout/fragment_library.xml
  app/src/main/res/layout/item_library_novel.xml
  app/src/main/res/layout/item_library_view_pager.xml
Labels: ♻️ [REFACTOR], 🗡️ 대장군 재원

#73 refactor: post view 브로드캐스트 로직 대체
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/dialog/PostSuccessDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
  app/src/main/res/layout/activity_post_novel.xml
Labels: ♻️ [REFACTOR], 🔮 법사 준서

#72 fix: search view 아이템이 겹치게 검색되는 오류 수정
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/search/SearchAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/search/searchViewModel/SearchViewModel.kt
Labels: 🔨 [FIX], 🔮 법사 준서

#75 fix: post view 분기처리 수정
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
Labels: 🔨 [FIX], 🔮 법사 준서

#78 refactor: my page QA 반영 및 기능 구현
  app/src/main/java/com/teamwss/websoso/data/mapper/AvatarMyPageResponseMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/AvatarResponseMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/SosoPickNovelResponseMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/UserInfoMyPageResponseMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/AvatarEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/SosoPickNovelEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserInfoMyPageEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/AvatarMyPageResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/SosopickNovelHomeResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserInfoMyPageResponse.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/AvatarService.kt
  app/src/main/java/com/teamwss/websoso/data/repository/AvatarRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adapter/HomeAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adapter/HomeViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/AvatarDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeNickName/ChangeNicknameActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeNickName/ChangeNicknameViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdpater.kt
  app/src/main/res/layout/activity_change_nickname.xml
  app/src/main/res/layout/dialog_avatar.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/raw/lottie_post_success.json
  app/src/main/res/raw/lottie_regressor_1.json
  app/src/main/res/raw/lottie_regressor_2.json
  app/src/main/res/raw/lottie_sosocat_1.json
  app/src/main/res/raw/lottie_sosocat_2.json
  app/src/main/res/raw/lottie_villainess_1.json
  app/src/main/res/raw/lottie_villainess_2.json
Labels: ♻️ [REFACTOR], 🗡️ 대장군 재원

#80 feat: 앱 아이콘 변경 및 스플래시 라이브러리 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/ic_app_logo-playstore.png
  app/src/main/res/drawable/ic_app_logo_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_app_logo.webp
  app/src/main/res/mipmap-hdpi/ic_app_logo_round.webp
  app/src/main/res/mipmap-mdpi/ic_app_logo.webp
  app/src/main/res/mipmap-mdpi/ic_app_logo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_app_logo.webp
  app/src/main/res/mipmap-xhdpi/ic_app_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_logo.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo_round.webp
  app/src/main/res/values/ic_app_logo_background.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#81 refactor: post view와 연결된 스택 정리
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
  app/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], 🔮 법사 준서

#85 feat: 스플래시 대응 및 기록 뷰에서 메모 삭제 시 스낵바 메시지 출력
  app/src/main/AndroidManifest.xml
  app/src/main/ic_app_logo-playstore.png
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
  app/src/main/res/drawable/ic_app_logo_foreground.xml
  app/src/main/res/mipmap-hdpi/ic_app_logo.webp
  app/src/main/res/mipmap-hdpi/ic_app_logo_round.webp
  app/src/main/res/mipmap-mdpi/ic_app_logo.webp
  app/src/main/res/mipmap-mdpi/ic_app_logo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_app_logo.webp
  app/src/main/res/mipmap-xhdpi/ic_app_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_logo.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo_round.webp
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/themes.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#86 refactor: 앱의 전반적인 ui 통일
  app/src/main/res/drawable/shape_nickname_cursor.xml
  app/src/main/res/layout/activity_change_nickname.xml
  app/src/main/res/layout/activity_check_user_info.xml
  app/src/main/res/layout/activity_memo_plain.xml
  app/src/main/res/layout/activity_memo_write.xml
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/activity_post_novel.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_library.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_record.xml
Labels: ♻️ [REFACTOR], 🔮 법사 준서

#87 feat: splash 엑티비티 생성 및 토큰 발급
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/App.kt
  app/src/main/java/com/teamwss/websoso/data/authInterceptor/AuthInterceptor.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/LoginRequest.kt
  app/src/main/java/com/teamwss/websoso/data/remote/service/AuthService.kt
  app/src/main/java/com/teamwss/websoso/data/repository/AuthRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/splash/SplashActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/splash/SplashViewModel.kt
  app/src/main/res/drawable-xhdpi/img_splash.png
  app/src/main/res/drawable-xxhdpi/img_splash.png
  app/src/main/res/drawable-xxxhdpi/img_splash.png
  app/src/main/res/drawable/img_splash.png
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/item_memo.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#90 refactor: style 수정
  app/src/main/java/com/teamwss/websoso/util/CustomSnackBar.kt
  app/src/main/res/values/typography.xml
Labels: ♻️ [REFACTOR], 🔮 법사 준서

#92 fix: 탭 아이템 선택 textColor 추가
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/fragment_library.xml
Labels: 🔨 [FIX], 🗡️ 대장군 재원

#96 feat: 두 번 클릭시 뒤로가기 경고메시지
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_post_novel.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#97 refactor: 메모 뷰 2차 실시간 QA 대응
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/fragment_novel_info.xml
Labels: ♻️ [REFACTOR], 🏹 궁사 명지

#99 refactor: 2차 qa 변경사항 반영
  app/src/main/res/layout/fragment_library.xml
Labels: ♻️ [REFACTOR], 🗡️ 대장군 재원

#101 refactor: 메모 뷰 3차 QA 반영
  app/src/main/java/com/teamwss/websoso/ui/memoPlain/MemoPlainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/res/layout/fragment_novel_info.xml
Labels: ♻️ [REFACTOR], 🏹 궁사 명지

#102 refactor: 메모 작성 시 키보드 뒤에 숨어지는 이슈 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteActivity.kt
  app/src/main/res/layout/activity_memo_plain.xml
  app/src/main/res/layout/activity_memo_write.xml
Labels: ♻️ [REFACTOR], 🏹 궁사 명지
