Repository Team-WSS/WSS-Android, pull requests merged in 2024-07, with the labels that each got.

#82 refactor: ValidateNicknameUseCase가 검증 책임을 가지도록 변경
  app/src/main/java/com/teamwss/websoso/domain/model/NicknameValidationRule.kt
  app/src/main/java/com/teamwss/websoso/domain/model/NicknameValidator.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/ValidateNicknameUseCase.kt
Labels: ♻️ [REFACTOR], 🗡️ 대장군 재원

#79 feat: 상세 탐색 정보 뷰 구현
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/model/Genre.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/res/color/bg_detail_explore_chip_background_selector.xml
  app/src/main/res/color/bg_detail_explore_chip_stroke_selector.xml
  app/src/main/res/color/bg_detail_explore_chip_text_selector.xml
  app/src/main/res/drawable/bg_detail_explore_white_radius_top_16dp.xml
  app/src/main/res/drawable/btn_detail_explore_modal_cancel.xml
  app/src/main/res/drawable/ic_detail_explore_reset.xml
  app/src/main/res/layout/dialog_detail_explore.xml
  app/src/main/res/layout/fragment_detail_explore_info.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#87 feat: 성별,출생년도 Onboarding UI 구현
  app/src/main/res/drawable/bg_onboarding_second_bottom_sheet_primary_100_radius_12dp.xml
  app/src/main/res/drawable/bg_onboarding_second_bottom_sheet_primary_20_radius_12dp.xml
  app/src/main/res/drawable/bg_onboarding_second_gray_50_radius_8dp.xml
  app/src/main/res/drawable/ic_onboarding_cancel.xml
  app/src/main/res/drawable/ic_onboarding_dropdown.xml
  app/src/main/res/drawable/ic_onboarding_second_selected.xml
  app/src/main/res/drawable/selector_onboarding_first_duplication_check_button_background.xml
  app/src/main/res/drawable/selector_onboarding_first_duplication_check_button_text_color.xml
  app/src/main/res/drawable/selector_onboarding_next_button_background.xml
  app/src/main/res/layout/dialog_novel_rating_date.xml
  app/src/main/res/layout/fragment_onboarding_first.xml
  app/src/main/res/layout/fragment_onboarding_second.xml
  app/src/main/res/layout/fragment_onboarding_second_bottom_sheet.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#80 feat: 일반 탐색 결과 비어있을 때 기능 구현
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreViewModel.kt
  app/src/main/res/layout/activity_normal_explore.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#85 feat: 작품정보 뷰 구글 권장 아키텍처 및 레포지토리 패턴 적용
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelInfoMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelInfoEntity.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelInfoRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelInfoMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/adapter/NovelDetailPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/ReadStatus.kt
  app/src/main/res/drawable/ic_novel_info_keyword_toggle_deselected.xml
  app/src/main/res/drawable/ic_novel_info_keyword_toggle_selected.xml
  app/src/main/res/drawable/ic_novel_info_toggle_selector.xml
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#104 feat: 상세탐색 키워드 xml 구현
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordViewModel.kt
  app/src/main/res/drawable/bg_detail_explore_keyword_gray50_radius_14dp.xml
  app/src/main/res/layout/fragment_detail_explore_keyword.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/typography.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#93 feat: 작품평가 뷰 키워드 부분 레포지토리 패턴 및 구글 권장 아키텍처 적용
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelRatingMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelRatingEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelRatingKeywordCategoryEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelRatingCategoriesResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelRatingKeywordCategoriesResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelRatingKeywordCategoryResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelRatingRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelRatingMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingDateDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/adapter/NovelRatingKeywordAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/adapter/NovelRatingKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiState.kt
  app/src/main/res/layout/dialog_novel_rating_keyword.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#78 feat: float to dp 확장함수 추가
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
Labels: 🍯 [FEAT], 🔮 법사 준서

#109 feat: 상세 탐색 키워드 검색 결과 뷰 구현
  app/src/main/res/drawable/btn_detail_explore_keyword_primary50_radius_14dp.xml
  app/src/main/res/drawable/ic_detail_explore_keyword_not_exist_result.xml
  app/src/main/res/layout/fragment_detail_explore_keyword.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#110 feat: 카테고리별 피드 조회 기능 구현
  app/src/main/java/com/teamwss/websoso/data/FakeApi.kt
  app/src/main/java/com/teamwss/websoso/data/repository/DefaultFeedRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetCategoryByUserGenderUseCase.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetFeedsUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/common/customView/WebsosoChip.kt
  app/src/main/java/com/teamwss/websoso/ui/common/customView/WebsosoChipGroup.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/adapter/FeedType.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/model/Category.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/model/CategoryModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/model/FeedUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/FeedMapper.kt
Labels: 🍯 [FEAT], ♻️ [REFACTOR], ⚖️ 재상 세훈

#115 refactor: 좋아요 기능 리팩터링
  app/src/main/java/com/teamwss/websoso/data/remote/api/FeedApi.kt
  app/src/main/java/com/teamwss/websoso/data/repository/DefaultFeedRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedScrollListener.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/util/SingleEventHandler.kt
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈

#116 feat: 더보기 기능 추가 구현
  app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/RepositoryModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/ServiceModule.kt
  app/src/main/java/com/teamwss/websoso/data/remote/ServiceModule.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/FeedApi.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetFeedsUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/common/base/BindingDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedItemClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/dialog/FeedRemoveDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/dialog/FeedReportDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/dialog/FeedReportDoneDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/model/FeedModel.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/FeedMapper.kt
  app/src/main/res/color/bg_popup_menu_content_text_selector.xml
  app/src/main/res/drawable/bg_dialog_remove_100_radius_8dp.xml
  app/src/main/res/drawable/ic_report_check.xml
  app/src/main/res/layout/dialog_remove_popup_menu.xml
  app/src/main/res/layout/dialog_report_done_popup_menu.xml
  app/src/main/res/layout/dialog_report_popup_menu.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/menu_feed_popup.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#117 refactor: 피드 아이템 상세 기능 리팩터링
  app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/RepositoryModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/ServiceModule.kt
  app/src/main/java/com/teamwss/websoso/data/remote/ServiceModule.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/FeedApi.kt
  app/src/main/java/com/teamwss/websoso/data/repository/DefaultFeedRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetFeedsUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/common/base/BindingDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedItemClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedScrollListener.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/dialog/FeedRemoveDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/dialog/FeedReportDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/dialog/FeedReportDoneDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/model/FeedModel.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/FeedMapper.kt
  app/src/main/java/com/teamwss/websoso/util/SingleEventHandler.kt
  app/src/main/res/color/bg_popup_menu_content_text_selector.xml
  app/src/main/res/drawable/bg_dialog_remove_100_radius_8dp.xml
  app/src/main/res/drawable/ic_report_check.xml
  app/src/main/res/layout/dialog_remove_popup_menu.xml
  app/src/main/res/layout/dialog_report_done_popup_menu.xml
  app/src/main/res/layout/dialog_report_popup_menu.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/menu_feed_popup.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🍯 [FEAT], ♻️ [REFACTOR], ⚖️ 재상 세훈

#121 feat: 로그인 요청 다이얼로그, 알림 엑티비티 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/notice/NoticeActivity.kt
  app/src/main/res/drawable-xhdpi/img_login_request.png
  app/src/main/res/drawable-xxhdpi/img_login_request.png
  app/src/main/res/drawable-xxxhdpi/img_login_request.png
  app/src/main/res/drawable/bg_login_request_primary_100_radius_8dp.xml
  app/src/main/res/drawable/bg_login_request_white_radius_12dp.xml
  app/src/main/res/drawable/ic_notice_back.xml
  app/src/main/res/drawable/img_login_request.png
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/dialog_login_request.xml
  app/src/main/res/layout/item_notice.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#125 feat: 피드 뷰 새로고침 기능 구현
  app/build.gradle.kts
  app/src/main/assets/lottie_websoso_loading.json
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedFragment.kt
  app/src/main/res/drawable/ic_btn_floating_write.xml
  app/src/main/res/layout/fragment_feed.xml
  settings.gradle.kts
Labels: 🍯 [FEAT]

#107 feat: 상세 탐색 정보 칩 viewModel에 저장
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreDialogBottomSheet.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/model/Rating.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/res/layout/fragment_detail_explore_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#99 feat: 작품정보 뷰 그래프 구현
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
  app/src/main/res/color/bg_novel_info_read_status_graph_selector.xml
  app/src/main/res/color/bg_novel_info_read_status_graph_text_selector.xml
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#98 feat: 작품정보 뷰 웹페이지 이동 추가
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiState.kt
  app/src/main/res/color/bg_novel_info_read_status_graph_selector.xml
  app/src/main/res/color/bg_novel_info_read_status_graph_text_selector.xml
  app/src/main/res/drawable-xhdpi/btn_novel_info_kakao.png
  app/src/main/res/drawable-xhdpi/btn_novel_info_naver.png
  app/src/main/res/drawable-xxhdpi/btn_novel_info_kakao.png
  app/src/main/res/drawable-xxhdpi/btn_novel_info_naver.png
  app/src/main/res/drawable/btn_novel_info_kakao.png
  app/src/main/res/drawable/btn_novel_info_naver.png
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#88 feat: 작품평가 뷰 구글 권장 아키텍처 및 레포지토리 패턴 적용
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelRatingMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelRatingEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelRatingKeywordCategoryEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelRatingKeywordEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelRatingKeywordCategoriesResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelRatingKeywordCategoryResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelRatingKeywordResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelRatingResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelRatingRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelRatingKeywordMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelRatingMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingDateBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/adapter/NovelRatingKeywordAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/adapter/NovelRatingKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/CharmPoint.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/DatePickerType.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/ReadStatus.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/util/RatingDateManager.kt
  app/src/main/res/layout/dialog_novel_rating_date.xml
  app/src/main/res/layout/dialog_novel_rating_keyword.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#134 feat: 상세 탐색 탭 및 선택에 따른 탭 UI 수정
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreDialogBottomSheet.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/model/SelectedFragmentTitle.kt
  app/src/main/res/drawable/bg_detail_explore_primary100_oval.xml
  app/src/main/res/layout/dialog_detail_explore.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#131 feat: WebsosoLoadingLayout 구현
  app/build.gradle.kts
  app/src/main/java/com/teamwss/websoso/ui/common/customView/WebsosoLoadingLayout.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/res/drawable-xhdpi/img_load_fail.png
  app/src/main/res/drawable-xxhdpi/img_load_fail.png
  app/src/main/res/drawable/bg_load_primary_100_radius_8dp.xml
  app/src/main/res/drawable/ic_load_load.gif
  app/src/main/res/drawable/img_load_fail.png
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/layout_loading.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#136 feat: retrofit2 라이브러리 버전업(2.9.0 to 2.11.0)
  app/build.gradle.kts
Labels: 🍯 [FEAT], 🏹 궁사 명지

#137 refactor: 피드 업데이트 기능 분기처리 리팩터링
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetFeedsUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedViewModel.kt
Labels: 🍯 [FEAT], ♻️ [REFACTOR], ⚖️ 재상 세훈

#139 feat: 마이페이지 sticky header 구현
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
  app/src/main/res/drawable/bg_my_library_gray50_radius_12dp.xml
  app/src/main/res/drawable/bg_my_library_gray50_radius_14dp.xml
  app/src/main/res/drawable/bg_my_library_primary50_radius_12dp.xml
  app/src/main/res/drawable/ic_book_closed_and_union.xml
  app/src/main/res/drawable/ic_lower_path.xml
  app/src/main/res/drawable/ic_pencil_circle_fill.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/ic_upper_path.xml
  app/src/main/res/drawable/img_user_pofile.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_my_activity.xml
  app/src/main/res/layout/fragment_my_library.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#145 feat: 마이페이지 내 서재 디폴트뷰 xml
  app/src/main/res/drawable-xhdpi/img_my_library_empty_cat.png
  app/src/main/res/drawable-xxhdpi/img_my_library_empty_cat.png
  app/src/main/res/drawable-xxxhdpi/img_my_library_empty_cat.png
  app/src/main/res/drawable/ic_my_library_navigate_right.xml
  app/src/main/res/layout/fragment_my_library.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#147 feat: 상세 탐색 결과 화면 xml 구현
  app/src/main/res/drawable/bg_detail_explore_result_gray50_radius_14dp.xml
  app/src/main/res/drawable/ic_detail_explore_result_filter.xml
  app/src/main/res/layout/activity_detail_explore_result.xml
  app/src/main/res/layout/item_detail_explore_result.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지
