Repository Team-WSS/WSS-Android, pull requests merged in 2024-06, with the labels that each got.

#58 build: manifest 액티비티명 수정 및 가로모드 방지
  app/src/main/AndroidManifest.xml
Labels: 🏹 궁사 명지, 🚧 [BUILD]

#60 feat: typhography 업데이트
  app/src/main/res/values/typography.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#63 feat: 바인딩 바텀시트 다이알로그 추가
  app/src/main/java/com/teamwss/websoso/ui/common/base/BindingBottomSheetDialog.kt
  app/src/main/res/values/themes.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#67 feat: 상세 탐색 정보 xml 구현
  app/src/main/res/drawable/btn_detail_explore_modal_cancel.xml
  app/src/main/res/drawable/ic_detail_explore_reset.xml
  app/src/main/res/layout/dialog_detail_explore.xml
  app/src/main/res/layout/fragment_detail_explore_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#64 feat: 일반 탐색 뷰 구현 및 더미데이터 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/data/model/NormalExploreEntity.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeSosoPickRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/model/NormalExploreUiState.kt
  app/src/main/res/drawable/bg_explore_gray50_radius_14dp.xml
  app/src/main/res/drawable/bg_explore_primary50_radius_14dp.xml
  app/src/main/res/drawable/bg_explore_stroke_gray70_radius_14dp.xml
  app/src/main/res/drawable/btn_explore_back.xml
  app/src/main/res/drawable/btn_explore_cancel.xml
  app/src/main/res/drawable/btn_explore_search.xml
  app/src/main/res/drawable/ic_explore_not_exist_result.xml
  app/src/main/res/drawable/ic_normal_explore_interested.xml
  app/src/main/res/drawable/ic_normal_explore_rating.xml
  app/src/main/res/drawable/img_normal_explore_test_cover.jpeg
  app/src/main/res/layout/activity_normal_explore.xml
  app/src/main/res/layout/item_normal_explore.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#62 feat: WebsosoChip closeIcon 추가
  app/src/main/java/com/teamwss/websoso/ui/common/customView/WebsosoChip.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordDialog.kt
Labels: 🍯 [FEAT], 🔮 법사 준서

#75 feat: 개쩌는 돌아방쓰 리드미 작성하기
  README.md
Labels: 🍯 [FEAT], 🔮 법사 준서

#73 feat: 작품상세 뷰 구글 권장 아키텍처 및 레포지토리 패턴 적용
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelDetailMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/gitkeep
  app/src/main/java/com/teamwss/websoso/data/model/NovelDetailEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelDetailResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelDetailRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelDetailMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelInfoMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailModel.kt
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/menu_novel_detail_popup.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#69 refactor: 작품정보 뷰 키워드 리사이클러뷰 마이그레이션
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelDetailMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/gitkeep
  app/src/main/java/com/teamwss/websoso/data/model/NovelDetailEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelDetailResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelInfoResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelDetailRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelDetailMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelInfoMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/layout/menu_novel_detail_popup.xml
Labels: ♻️ [REFACTOR], 🔮 법사 준서

#76 feat: 상세 탐색 정보 칩 구현
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/model/Genre.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/res/color/bg_detail_explore_chip_background_selector.xml
  app/src/main/res/color/bg_detail_explore_chip_stroke_selector.xml
  app/src/main/res/color/bg_detail_explore_chip_text_selector.xml
  app/src/main/res/layout/dialog_detail_explore.xml
  app/src/main/res/layout/fragment_detail_explore_info.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지
