Repository Team-WSS/WSS-Android, pull requests merged in 2024-04, with the labels that each got.

#9 feat: 프레그먼트 컨테이너 뷰 생성 및 바텀 네비게이션과 연결
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#20 fix: 문제가 있는 디자인 시스템 수정
  app/src/main/res/values/colors.xml
  app/src/main/res/values/typography.xml
Labels: 🔨 [FIX], 🔮 법사 준서

#22 feat: 작품정보 뷰 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/adapter/NovelDetailPagerAdapter.kt
  app/src/main/res/drawable/bg_novel_detail_white_radius_10dp.xml
  app/src/main/res/drawable/bg_novel_detail_white_radius_15dp.xml
  app/src/main/res/drawable/ic_novel_detail_feed.xml
  app/src/main/res/drawable/ic_novel_detail_genre_test.xml
  app/src/main/res/drawable/ic_novel_detail_interest.xml
  app/src/main/res/drawable/ic_novel_detail_menu.xml
  app/src/main/res/drawable/ic_novel_detail_navigate_back.xml
  app/src/main/res/drawable/ic_novel_detail_rating.xml
  app/src/main/res/drawable/ic_novel_detail_review.xml
  app/src/main/res/drawable/img_novel_detail_cover_foreground.xml
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/fragment_novel_feed.xml
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#17 feat: 피드 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/WebsosoApp.kt
  app/src/main/java/com/teamwss/websoso/data/model/FeedEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/FeedsEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/gitkeep
  app/src/main/java/com/teamwss/websoso/data/remote/response/FeedResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/FeedsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/gitkeep
  app/src/main/java/com/teamwss/websoso/data/repository/FakeFeedRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeUserRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/gitkeep
  app/src/main/java/com/teamwss/websoso/domain/mapper/FeedMapper.kt
  app/src/main/java/com/teamwss/websoso/domain/model/Feed.kt
  app/src/main/java/com/teamwss/websoso/domain/model/Feeds.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetFeedsUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/common/base/BaseDiffUtil.kt
  app/src/main/java/com/teamwss/websoso/ui/common/base/BindingFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/common/customView/WebsosoChip.kt
  app/src/main/java/com/teamwss/websoso/ui/common/customView/WebsosoChipGroup.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedItemClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/adapter/FeedAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/adapter/FeedViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/model/Category.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/model/FeedUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/FeedMapper.kt
  app/src/main/java/com/teamwss/websoso/util/gitkeep
  app/src/main/res/color/bg_feed_chip_background_selector.xml
  app/src/main/res/color/bg_feed_chip_stroke_selector.xml
  app/src/main/res/color/bg_feed_chip_text_selector.xml
  app/src/main/res/drawable/bg_feed_indicator.xml
  app/src/main/res/drawable/bg_feed_popup.xml
  app/src/main/res/drawable/btn_feed_novel_info.xml
  app/src/main/res/drawable/btn_feed_thumb_up.xml
  app/src/main/res/drawable/ic_comment.xml
  app/src/main/res/drawable/ic_link.xml
  app/src/main/res/drawable/ic_more.xml
  app/src/main/res/drawable/ic_navigate_right.xml
  app/src/main/res/drawable/ic_pencil.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/drawable/ic_thumb_up.xml
  app/src/main/res/drawable/ic_thumb_up_on.xml
  app/src/main/res/layout/activity_feed_detail.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/menu_feed_popup.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#36 fix: 모듈간 의존성 순환 참조
  Domain/.gitignore
  Domain/build.gradle.kts
  Domain/src/main/java/com/teamwss/domain/Domain.kt
  app/build.gradle.kts
  settings.gradle.kts
Labels: ⚖️ 재상 세훈, 🔨 [FIX]
