Repository Team-WSS/WSS-Android, pull requests merged in 2024-09, with the labels that each got.

#288 feat: 일반 검색 1차 QA 대응
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/res/layout/activity_blocked_users.xml
  app/src/main/res/layout/activity_normal_explore.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/values/themes.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#274 feat: 다른유저 프로필 조회 api 연결
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/OtherUserProfileEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/OtherUserProfileResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageViewModel.kt
  app/src/main/res/layout/activity_other_user_page.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#305 feat: 로그인 1차 QA 대응
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/item_login_image.xml
Labels: 🍯 [FEAT], 🔨 [FIX], 🗡️ 대장군 재원, 🚨[Emergency]

#303 feat: 작품피드 1차 QA 대응
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_novel_feed.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#302 feat: 작품정보 1차 QA 대응
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#301 feat: 작품상세 1차 QA 대응
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelDetailEntity.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailAppBar.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailCoverDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/res/drawable/ic_novel_rating_exit.xml
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/dialog_novel_detail_cover.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_novel_feed.xml
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/layout/menu_novel_detail_popup.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#304 feat: 상세탐색 1차 QA 대응
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreDialogBottomSheet.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultKeywordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/res/layout/fragment_detail_explore_keyword.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/item_common_keyword.xml
  app/src/main/res/values/deepLinks.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#306 feat: 온보딩 1차 QA 대응
  app/src/main/java/com/teamwss/websoso/common/util/ExtentionFuction.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/ValidateNicknameUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/first/OnboardingFirstFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/third/model/Genre.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/welcome/WelcomeActivity.kt
  app/src/main/res/drawable/bg_onboarding_primary50_radius_20dp.xml
  app/src/main/res/drawable/selector_onboarding_first_duplication_check_button_background.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_welcome.xml
  app/src/main/res/layout/fragment_onboarding_first.xml
  app/src/main/res/layout/fragment_onboarding_second.xml
  app/src/main/res/layout/fragment_onboarding_third.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#307 feat: 작품평가 뷰 1차 QA 대응
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingDateBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/adapter/NovelRatingKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/CharmPoint.kt
  app/src/main/res/drawable-xhdpi/ic_novel_rating_star_filled.png
  app/src/main/res/drawable-xhdpi/ic_novel_rating_star_unfilled.png
  app/src/main/res/drawable-xxhdpi/ic_novel_rating_star_filled.png
  app/src/main/res/drawable-xxhdpi/ic_novel_rating_star_unfilled.png
  app/src/main/res/drawable/ic_novel_rating_star_filled.png
  app/src/main/res/drawable/ic_novel_rating_star_filled_selector.xml
  app/src/main/res/drawable/ic_novel_rating_star_selector.xml
  app/src/main/res/drawable/ic_novel_rating_star_unfilled.png
  app/src/main/res/drawable/ic_novel_rating_star_unfilled_selector.xml
  app/src/main/res/layout/activity_novel_rating.xml
  app/src/main/res/layout/dialog_novel_rating_keyword.xml
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#309 feat: 탐색 및 설정 뷰 수정된 디자인 반영
  app/src/main/java/com/teamwss/websoso/common/util/BindingAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/ChangeUserInfoActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/setting/SettingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/first/WithdrawFirstActivity.kt
  app/src/main/res/drawable/btn_setting_back.xml
  app/src/main/res/layout/activity_account_info.xml
  app/src/main/res/layout/activity_blocked_users.xml
  app/src/main/res/layout/activity_change_user_info.xml
  app/src/main/res/layout/activity_detail_explore_result.xml
  app/src/main/res/layout/activity_normal_explore.xml
  app/src/main/res/layout/activity_profile_disclosure.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_withdraw_first.xml
  app/src/main/res/layout/activity_withdraw_second.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/item_blocked_user.xml
  app/src/main/res/layout/item_detail_explore_result.xml
  app/src/main/res/layout/item_normal_explore.xml
  app/src/main/res/layout/item_soso_pick.xml
  app/src/main/res/values/deepLinks.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#311 feat: 아바타 변경 기능 추가
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/layout/item_profile_edit_avatar.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#312 feat: 홈 1차 QA 대응
  app/src/main/java/com/teamwss/websoso/data/mapper/FeedMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserInterestFeedsEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserInterestFeedsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeCustomItemDecoration.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/PopularNovelsAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/UserInterestFeedAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/model/HomeUiState.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_popular_novel.xml
  app/src/main/res/layout/item_recommended_novel_by_user_taste.xml
  app/src/main/res/layout/item_user_interest_feed.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#316 feat: 앱 평점 남기기 버튼 제거
  app/src/main/java/com/teamwss/websoso/ui/setting/SettingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/setting/SettingClickListener.kt
  app/src/main/res/layout/activity_setting.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#319 feat: GetS3ImageUrl 구현
  app/build.gradle.kts
  app/src/main/java/com/teamwss/websoso/common/util/ExtentionFuction.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/PopularNovelsViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/UserInterestFeedViewHolder.kt
  app/src/main/res/layout/item_popular_novel.xml
  app/src/main/res/layout/item_user_interest_feed.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#322 feat: 탐색 및 설정 뷰에 있는 svg > png 로 수정
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/adapter/BlockedUsersViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/adapter/NovelRatingKeywordViewHolder.kt
  app/src/main/res/layout/item_blocked_user.xml
  app/src/main/res/layout/item_common_keyword.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#314 feat: 피드작성 1차 QA 대응(+ 수정하기 기능 구현)
  app/src/main/java/com/teamwss/websoso/common/ui/base/BaseActivity.kt
  app/src/main/java/com/teamwss/websoso/common/util/ExtentionFuction.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelPreferenceEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/FeedApi.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetDetailExploreResultUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedSearchNovelBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreatingFeedDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/model/CreateFeedCategory.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/model/CreatedFeedCategoryModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/EditFeedModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/model/Category.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelAlertDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailAppBar.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailCoverDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingDateBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/Genre.kt
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], ♻️ [REFACTOR], ⚖️ 재상 세훈

#324 feat: 피드 1차 QA 대응
  app/src/main/java/com/teamwss/websoso/common/ui/custom/WebsosoChip.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedItemClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/adapter/FeedAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/adapter/FeedNoMoreViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/adapter/FeedType.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/adapter/FeedViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/dialog/FeedRemoveDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/dialog/FeedReportDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/dialog/FeedReportDoneDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_feed_no_more.xml
  app/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈

#318 feat: 보관함 ui 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/data/model/StorageEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserFeedsEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserFeedsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeStorageRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserFeedRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/model/MyProfileModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/ActivityModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/UserProfileModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/ActivityMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/MyActivityDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageItemAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageItemViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageViewPagerViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/model/StorageTabs.kt
  app/src/main/res/drawable/bg_storage_primary50_radius_12dp.xml
  app/src/main/res/drawable/ic_storage_arrow_down.xml
  app/src/main/res/drawable/ic_storage_null.xml
  app/src/main/res/drawable/ic_storage_star.xml
  app/src/main/res/layout/activity_storage.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_my_activity.xml
  app/src/main/res/layout/item_storage.xml
  app/src/main/res/layout/item_storage_novel.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#334 feat: 2차 QA 해리 담당 대응
  app/src/main/java/com/teamwss/websoso/domain/usecase/ValidateNicknameUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/model/HomeUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/model/MainUiState.kt
  app/src/main/res/drawable-xhdpi/img_login_4.png
  app/src/main/res/drawable-xxhdpi/img_login_4.png
  app/src/main/res/drawable-xxxhdpi/img_login_4.png
  app/src/main/res/drawable/img_login_4.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#326 feat: 탐색 및 설정 뷰 싱글이벤트 적용
  app/src/main/java/com/teamwss/websoso/ui/accountInfo/LogoutDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/BlockedUsersActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/ChangeUserInfoActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreDialogBottomSheet.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultDialogBottomSheet.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultKeywordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/second/WithdrawSecondActivity.kt
  app/src/main/res/drawable/bg_snack_bar_gray_cc_394258_radius_4dp.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#340 feat: 회원탈퇴 첫번째 화면 아이콘 수정
  app/src/main/res/drawable/ic_withdraw_interested.xml
  app/src/main/res/layout/activity_withdraw_first.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#338 feat: 전체적인 상단 마진값 수정
  app/src/main/res/layout/activity_account_info.xml
  app/src/main/res/layout/activity_activity_detail.xml
  app/src/main/res/layout/activity_blocked_users.xml
  app/src/main/res/layout/activity_change_user_info.xml
  app/src/main/res/layout/activity_create_feed.xml
  app/src/main/res/layout/activity_detail_explore_result.xml
  app/src/main/res/layout/activity_feed_detail.xml
  app/src/main/res/layout/activity_normal_explore.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_other_user_page.xml
  app/src/main/res/layout/activity_profile_disclosure.xml
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_storage.xml
  app/src/main/res/layout/activity_withdraw_first.xml
  app/src/main/res/layout/activity_withdraw_second.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#337 feat: 데이타스토어 정비 및 기능 추가
  app/src/main/java/com/teamwss/websoso/common/util/ExtentionFuction.kt
  app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/RepositoryModule.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserPreferencesRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/splash/SplashActivity.kt
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/dialog_novel_detail_cover.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#345 feat: 온보딩, 홈 UX 라이팅 변경
  app/src/main/res/layout/fragment_onboarding_third.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#346 refactor: activity result API 상수 -> 공통 enum class 리팩터링
  app/src/main/java/com/teamwss/websoso/common/ui/model/ResultFrom.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈

#348 feat: 상세 탐색 화면 로그인 여부에 따른 분기 처리
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#353 refactor: 네트워크 오류 UX 라이팅 수정
  app/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], 🔮 법사 준서

#361 feat: 마이페이지 svg 이미지 png 적용 및 s3 로직 적용
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/model/MyPageUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/adapter/RestGenrePreferenceAdapter.kt
  app/src/main/res/layout/fragment_my_library.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_user_interest_feed.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#352 feat: 프로필변경 뷰 API 추가 및 이동 방식 변경
  app/src/main/java/com/teamwss/websoso/ui/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/adapter/AvatarChangeViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/ProfileEditUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/ProfileEditUiState.kt
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#343 feat: home onResume() 서버통신 로직 제거 후 구현
  app/src/main/java/com/teamwss/websoso/common/ui/model/ResultFrom.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/model/HomeUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/model/MainUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
  app/src/main/res/drawable/ic_my_page_edit_profile.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], 🗡️ 대장군 재원

#358 feat: 프로필 공개여부 수정 시 스낵바 메시지 출력 및 UX라이팅 수정
  app/src/main/java/com/teamwss/websoso/common/ui/model/ResultFrom.kt
  app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/setting/SettingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/setting/SettingClickListener.kt
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/dialog_onboarding_birth_year.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#359 feat: 성별/나이 변경 시 스낵바 메시지 출력
  app/src/main/java/com/teamwss/websoso/common/ui/model/ResultFrom.kt
  app/src/main/java/com/teamwss/websoso/ui/accountInfo/AccountInfoActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/ChangeUserInfoActivity.kt
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#363 feat: 작품평가 뷰 2차 QA 반영
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelAlertDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelAlertModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/res/drawable/bg_novel_detail_primary_100_radius_8dp.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#362 feat: 작품상세 뷰 2차 QA 반영
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelAlertDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelAlertModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/Platform.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/ReadStatus.kt
  app/src/main/res/drawable/bg_novel_detail_primary_100_radius_8dp.xml
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/layout/menu_novel_detail_popup.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#356 feat: 유저 차단하기 ui 구현 및 api 연결 
  app/src/main/java/com/teamwss/websoso/common/ui/model/ResultFrom.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/BlockUserDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageViewModel.kt
  app/src/main/res/drawable/btn_block_user.xml
  app/src/main/res/layout/dialog_block_user.xml
  app/src/main/res/layout/menu_other_user_page_popup.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#347 feat: 보관함 api 연결
  app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/StorageEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserStorageEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserStorageResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeStorageRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageItemAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageItemViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageViewPagerViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/storage/model/StorageTabs.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/SortMenuHandler.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/SortPopupHandler.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageItemAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageItemViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageViewPagerViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/model/SortType.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/model/StatusTabs.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/model/UserStorageModel.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/model/UserStorageUiState.kt
  app/src/main/res/layout/activity_storage.xml
  app/src/main/res/layout/item_storage.xml
  app/src/main/res/layout/item_storage_novel.xml
  app/src/main/res/layout/menu_storage_popup.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#366 fix: 보관함 클래스명 변경 수정
  app/src/main/AndroidManifest.xml
Labels: 🍯 [FEAT], 👛 황후 연진, 🚨[Emergency]

#367 feat: 유저의 userId, userNickname을 받아오는 api 연결 및 dataStore 저장 로직 구현
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserInfoDetailEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserInfoEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserInfoDetailResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserInfoResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/accountInfo/AccountInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/ChangeUserInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/model/MainUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
Labels: 🍯 [FEAT], 🗡️ 대장군 재원, 🚨[Emergency]

#364 feat: 내 활동 API 연결
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserFeedsEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserFeedsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/adapter/MyActivityAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/adapter/MyActivityViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/ActivitiesModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/ActivityModel.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/ActivityMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/adapter/OtherUserActivityAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/adapter/OtherUserActivityViewHolder.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_my_activity.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#373 feat: 다이얼로그 모서리값 12dp > 14dp 로 수정
  app/src/main/res/drawable/bg_feed_popup.xml
  app/src/main/res/drawable/bg_login_request_white_radius_14dp.xml
  app/src/main/res/drawable/bg_logout_white_radius_14dp.xml
  app/src/main/res/drawable/bg_novel_detail_white_radius_12dp.xml
  app/src/main/res/layout/dialog_block_user.xml
  app/src/main/res/layout/dialog_login_request.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/dialog_novel_alert.xml
  app/src/main/res/layout/dialog_remove_popup_menu.xml
  app/src/main/res/layout/dialog_report_done_popup_menu.xml
  app/src/main/res/layout/dialog_report_popup_menu.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#374 fix: 타유저 프로필 방문 후 뒤로가기 버튼 눌렀을 때 띄워지는 스낵바 해결
  app/src/main/java/com/teamwss/websoso/common/ui/model/ResultFrom.kt
Labels: 🏹 궁사 명지, 🔨 [FIX]

#381 feat:본인 여부에 따라 MyPage 혹은 OtherUserPage로 이동하는 로직 구현
  app/src/main/java/com/teamwss/websoso/common/ui/model/ResultFrom.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/notice/NoticeActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageActivity.kt
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#382 feat: 피드 상세보기 뷰 1, 2차 QA 대응
  app/src/main/java/com/teamwss/websoso/common/ui/model/ResultFrom.kt
  app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/CommentClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailCommentViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailContentViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/dialog/RemovedFeedDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/FeedDetailUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/res/drawable/bg_removed_feed_gray_70_radius_8dp.xml
  app/src/main/res/drawable/btn_comment_register_off.xml
  app/src/main/res/drawable/btn_comment_register_on.xml
  app/src/main/res/drawable/btn_comment_register_selector.xml
  app/src/main/res/layout/activity_feed_detail.xml
  app/src/main/res/layout/dialog_feed_removed_popup_menu.xml
  app/src/main/res/layout/item_feed_detail_comment.xml
  app/src/main/res/layout/item_feed_detail_header.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#368 feat: 작품 상세 화면 로그인 여부에 따른 분기 처리
  app/src/main/java/com/teamwss/websoso/common/ui/model/ResultFrom.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/adapter/NovelDetailPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/res/layout/activity_novel_detail.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#384 feat: 성별을 dataStore에 저장하는 로직 구현
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserInfoEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserInfoResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#385 feat: 다른유저 활동 피드 api 연결 및 다른유저 s3 이미지 적용
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/ActivityItemClickHandler.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/ActivityItemClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/adapter/MyActivityAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/adapter/MyActivityViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/ActivitiesModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/ActivityLikeState.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/adapter/OtherUserPageViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/adapter/OtherUserActivityAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/adapter/OtherUserActivityViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/adapter/RestGenrePreferenceAdapter.kt
  app/src/main/res/layout/activity_other_user_page.xml
  app/src/main/res/layout/fragment_other_user_library.xml
  app/src/main/res/layout/item_my_activity.xml
  app/src/main/res/layout/item_rest_genre.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#388 refactor: 피드 뷰 2차 QA 대응
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/model/FeedUiState.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈

#390 feat: 보관함 갯수 api 변경 사항 대응
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/first/WithdrawFirstViewModel.kt
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#392 feat: 마이페이지 userId 불러오지 않는 현상 해결
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/adapter/RestGenrePreferenceAdapter.kt
  app/src/main/res/layout/item_rest_genre.xml
Labels: 👛 황후 연진, 🔨 [FIX], 🗡️ 대장군 재원

#393 refactor: 피드 작성하기 뷰 2차 QA 대응
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreatingFeedDialogFragment.kt
  app/src/main/res/layout/activity_create_feed.xml
  app/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈

#397 feat: 3차 QA 해리 담당 대응
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/item_popular_novel.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#398 feat: 공지 자세히 보기 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/notice/NoticeActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/notice/adapter/NoticeAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/notice/adapter/NoticeViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/notice/model/NoticeModel.kt
  app/src/main/java/com/teamwss/websoso/ui/noticeDetail/NoticeDetailActivity.kt
  app/src/main/res/layout/activity_notice_detail.xml
  app/src/main/res/layout/item_notice.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원
