Repository Team-WSS/WSS-Android, pull requests merged in 2024-05, with the labels that each got.

#19 feat: 탐색 뷰 메인화면 구현
  app/src/main/java/com/teamwss/websoso/WebsosoApp.kt
  app/src/main/java/com/teamwss/websoso/data/model/SosoPickEntity.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeSosoPickRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/explore/ExploreFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/adapter/SosoPickAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/adapter/SosoPickViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/model/SosoPickUiState.kt
  app/src/main/res/drawable/bg_explore_primary20_radius_14dp.xml
  app/src/main/res/drawable/btn_explore_gray50_radius_14dp.xml
  app/src/main/res/drawable/btn_explore_white_radius_14dp.xml
  app/src/main/res/drawable/ic_explore_genre_fifth.xml
  app/src/main/res/drawable/ic_explore_genre_first.xml
  app/src/main/res/drawable/ic_explore_genre_fourth.xml
  app/src/main/res/drawable/ic_explore_genre_second.xml
  app/src/main/res/drawable/ic_explore_genre_third.xml
  app/src/main/res/drawable/ic_explore_search.xml
  app/src/main/res/drawable/ic_explore_soso_pick.xml
  app/src/main/res/drawable/img_explore_test_cover.jpeg
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/item_soso_pick.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#38 feat: splash 기능 구현, login view viewpager 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/login/LoginActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/login/LoginViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/login/adapter/ImageViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/login/adapter/ImageViewPagerViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/splash/SplashActivity.kt
  app/src/main/res/drawable-xhdpi/img_login_1.png
  app/src/main/res/drawable-xhdpi/img_login_2.png
  app/src/main/res/drawable-xhdpi/img_login_3.png
  app/src/main/res/drawable-xhdpi/img_splash_background.png
  app/src/main/res/drawable-xxhdpi/img_login_1.png
  app/src/main/res/drawable-xxhdpi/img_login_2.png
  app/src/main/res/drawable-xxhdpi/img_login_3.png
  app/src/main/res/drawable-xxhdpi/img_splash_background.png
  app/src/main/res/drawable-xxxhdpi/img_login_1.png
  app/src/main/res/drawable-xxxhdpi/img_login_2.png
  app/src/main/res/drawable-xxxhdpi/img_login_3.png
  app/src/main/res/drawable-xxxhdpi/img_splash_background.png
  app/src/main/res/drawable/ic_login_kakao.xml
  app/src/main/res/drawable/ic_splash_icon.xml
  app/src/main/res/drawable/ic_splash_typo.xml
  app/src/main/res/drawable/img_login_1.png
  app/src/main/res/drawable/img_login_2.png
  app/src/main/res/drawable/img_login_3.png
  app/src/main/res/drawable/img_splash_background.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_login_image.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#31 feat: 작품소개 뷰 구현
  app/build.gradle.kts
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailAppBar.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/adapter/NovelDetailPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
  app/src/main/res/drawable-xhdpi/btn_novel_info_kakao.png
  app/src/main/res/drawable-xhdpi/btn_novel_info_naver.png
  app/src/main/res/drawable-xhdpi/img_novel_info_none.png
  app/src/main/res/drawable-xxhdpi/btn_novel_info_kakao.png
  app/src/main/res/drawable-xxhdpi/btn_novel_info_naver.png
  app/src/main/res/drawable-xxhdpi/img_novel_info_none.png
  app/src/main/res/drawable/bg_novel_detail_cover_background.xml
  app/src/main/res/drawable/bg_novel_detail_white_radius_12dp.xml
  app/src/main/res/drawable/bg_novel_detail_white_radius_14dp.xml
  app/src/main/res/drawable/bg_novel_detail_white_radius_bottom_14dp.xml
  app/src/main/res/drawable/bg_novel_detail_white_radius_top_14dp.xml
  app/src/main/res/drawable/bg_novel_info_gray_50_radius_12dp.xml
  app/src/main/res/drawable/bg_novel_info_gray_50_radius_8dp.xml
  app/src/main/res/drawable/bg_novel_info_primary_100_radius_8dp.xml
  app/src/main/res/drawable/bg_novel_info_primary_50_radius_20dp.xml
  app/src/main/res/drawable/btn_novel_info_kakao.png
  app/src/main/res/drawable/btn_novel_info_naver.png
  app/src/main/res/drawable/ic_novel_detail_menu.xml
  app/src/main/res/drawable/ic_novel_detail_navigate_back.xml
  app/src/main/res/drawable/ic_novel_detail_warning.xml
  app/src/main/res/drawable/img_novel_detail_cover_foreground.xml
  app/src/main/res/drawable/img_novel_info_none.png
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/dialog_novel_detail_remove_evaluate.xml
  app/src/main/res/layout/fragment_novel_feed.xml
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/layout/item_novel_info_reviews.xml
  app/src/main/res/layout/menu_novel_detail_popup.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#51 feat: Hilt 마이그레이션
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/WebsosoApp.kt
  app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeFeedRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeSosoPickRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeUserRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetFeedsUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/login/LoginActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/login/LoginViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/splash/SplashActivity.kt
  build.gradle.kts
Labels: 🍯 [FEAT], ♻️ [REFACTOR], ⚖️ 재상 세훈, 🏹 궁사 명지, 👛 황후 연진, 🔮 법사 준서, 🗡️ 대장군 재원

#50 feat: 온보딩 nickname 닉네임 검증 및 화면 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/domain/model/NicknameValidationRule.kt
  app/src/main/java/com/teamwss/websoso/domain/model/NicknameValidator.kt
  app/src/main/java/com/teamwss/websoso/domain/model/ValidationResult.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/ValidateNicknameUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/first/OnboardingFirstFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/first/model/NicknameInputType.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/first/model/OnboardingFirstUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/first/model/OnboardingFirstUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/model/OnboardingPage.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/second/OnboardingSecondFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/third/OnboardingThirdFragment.kt
  app/src/main/res/drawable/bg_onboarding_gray50_radius_12dp.xml
  app/src/main/res/drawable/bg_onboarding_gray70_radius_14dp.xml
  app/src/main/res/drawable/bg_onboarding_primary100_radius_14dp.xml
  app/src/main/res/drawable/bg_onboarding_primary50_radius_12dp.xml
  app/src/main/res/drawable/bg_onboarding_rect_progress.xml
  app/src/main/res/drawable/bg_onboarding_rect_progress_background.xml
  app/src/main/res/drawable/bg_onboarding_white_radius_12dp_border_gray70_1dp.xml
  app/src/main/res/drawable/bg_onboarding_white_radius_12dp_border_primary100_1dp.xml
  app/src/main/res/drawable/bg_onboarding_white_radius_12dp_border_secondary100_1dp.xml
  app/src/main/res/drawable/ic_onboarding_first_input_clear_complete.xml
  app/src/main/res/drawable/ic_onboarding_first_input_clear_default.xml
  app/src/main/res/drawable/ic_onboarding_first_input_clear_error.xml
  app/src/main/res/drawable/ic_onboarding_navigate_back_left.xml
  app/src/main/res/drawable/selc_onboarding_first_duplication_check_button_background.xml
  app/src/main/res/drawable/selc_onboarding_first_duplication_check_button_text_color.xml
  app/src/main/res/drawable/selc_onboarding_first_next_button_background.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_first.xml
  app/src/main/res/layout/fragment_onboarding_second.xml
  app/src/main/res/layout/fragment_onboarding_third.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원
