Repository Team-WSS/WSS-Android, pull requests merged in 2024-12, with the labels that each got.

#483 feat: 활동디테일 피드가 뜨지 않는 문제 해결
  app/src/main/java/com/into/websoso/ui/main/myPage/MyPageViewModel.kt
Labels: 👛 황후 연진, 🔨 [FIX]

#484 feat: 5차 QA 반영
  app/src/main/res/layout/activity_other_user_page.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#486 feat: 다른유저 보관함 null 화면 분기처리
  app/src/main/java/com/into/websoso/ui/userStorage/UserStorageActivity.kt
Labels: ♻️ [REFACTOR], 👛 황후 연진

#488 fix: 스크롤 초기화 버그 및 장르 영역 수정
  app/src/main/java/com/into/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/into/websoso/ui/main/feed/FeedViewModel.kt
  app/src/main/res/layout/item_feed.xml
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈, 🔨 [FIX]

#498 feat: 앰플리튜드 이벤트 트래커 도입
  app/build.gradle.kts
  app/src/main/java/com/into/websoso/common/util/tracker/Tracker.kt
  app/src/main/java/com/into/websoso/common/util/tracker/amplitude/AmplitudeTracker.kt
  app/src/main/java/com/into/websoso/common/util/tracker/di/TrackerModule.kt
  app/src/main/java/com/into/websoso/ui/accountInfo/AccountInfoActivity.kt
  app/src/main/java/com/into/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/into/websoso/ui/createFeed/CreateFeedSearchNovelBottomSheetDialog.kt
  app/src/main/java/com/into/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
  app/src/main/java/com/into/websoso/ui/detailExploreResult/DetailExploreResultKeywordFragment.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/java/com/into/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/into/websoso/ui/main/feed/dialog/FeedReportDialogFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/into/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/java/com/into/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/novelInfo/NovelInfoFragment.kt
  app/src/main/java/com/into/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/into/websoso/ui/otherUserPage/BlockUserDialogFragment.kt
  app/src/main/java/com/into/websoso/ui/otherUserPage/OtherUserPageActivity.kt
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#494 fix: 툴팁 윈도우 튕김 오류 해결
  app/src/main/java/com/into/websoso/ui/novelDetail/NovelDetailActivity.kt
Labels: 🔨 [FIX], 🔮 법사 준서

#495 feat: 마이페이지 스티키헤더 스크롤 문제 해결
  app/src/main/java/com/into/websoso/ui/profileEdit/ProfileEditActivity.kt
  app/src/main/res/layout/activity_other_user_page.xml
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: 👛 황후 연진, 🔨 [FIX]

#491 feat: 최소버전 강제 업데이트 구현
  app/src/main/java/com/into/websoso/data/di/ApiModule.kt
  app/src/main/java/com/into/websoso/data/di/RepositoryModule.kt
  app/src/main/java/com/into/websoso/data/mapper/VersionMapper.kt
  app/src/main/java/com/into/websoso/data/model/MinimumVersionEntity.kt
  app/src/main/java/com/into/websoso/data/remote/api/VersionApi.kt
  app/src/main/java/com/into/websoso/data/remote/response/MinimumVersionResponseDto.kt
  app/src/main/java/com/into/websoso/data/repository/VersionRepository.kt
  app/src/main/java/com/into/websoso/ui/splash/SplashActivity.kt
  app/src/main/java/com/into/websoso/ui/splash/SplashViewModel.kt
  app/src/main/java/com/into/websoso/ui/splash/dialog/MinimumVersionDialogFragment.kt
  app/src/main/res/layout/dialog_minimum_version_popup_menu.xml
  app/src/main/res/values/deepLinks.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#500 feat: 앱 내 공지 하이퍼링크 구현
  app/src/main/java/com/into/websoso/ui/noticeDetail/NoticeDetailActivity.kt
  app/src/main/res/layout/activity_notice_detail.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#502 feat: 비로그인 로직을 제거
  app/src/main/res/layout/activity_login.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#505 build: ktlint CI 적용
  .editorconfig
  .github/workflows/WSS_PR_builder.yml
Labels: ⚖️ 재상 세훈, 🏹 궁사 명지, 🚧 [BUILD]

#504 feat: 소소한 수다 카테고리 선택시 이벤트 트래킹 수정
  app/src/main/java/com/into/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/into/websoso/ui/main/feed/model/Category.kt
Labels: 🍯 [FEAT], 🗡️ 대장군 재원
