Repository Team-WSS/WSS-Android, pull requests merged in 2024-08, with the labels that each got.

#133 feat: 작품정보 뷰 API 구현
  app/build.gradle.kts
  app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelInfoRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/NovelRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelInfoMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/adapter/NovelDetailPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiState.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#138 feat: 피드 기능 구현
  app/build.gradle.kts
  app/src/main/assets/lottie_websoso_loading.json
  app/src/main/java/com/teamwss/websoso/data/FakeApi.kt
  app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/RepositoryModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/ServiceModule.kt
  app/src/main/java/com/teamwss/websoso/data/remote/ServiceModule.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/FeedApi.kt
  app/src/main/java/com/teamwss/websoso/data/repository/DefaultFeedRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetCategoryByUserGenderUseCase.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetFeedsUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/common/base/BindingDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/common/customView/WebsosoChip.kt
  app/src/main/java/com/teamwss/websoso/ui/common/customView/WebsosoChipGroup.kt
  app/src/main/java/com/teamwss/websoso/ui/common/customView/WebsosoLoadingLayout.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedItemClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedScrollListener.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/adapter/FeedLoadingViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/adapter/FeedType.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/dialog/FeedRemoveDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/dialog/FeedReportDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/dialog/FeedReportDoneDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/model/Category.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/model/CategoryModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/model/FeedModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/model/FeedUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/FeedMapper.kt
  app/src/main/java/com/teamwss/websoso/util/SingleEventHandler.kt
  app/src/main/res/color/bg_popup_menu_content_text_selector.xml
  app/src/main/res/drawable-xhdpi/img_novel_info_none.png
  app/src/main/res/drawable-xxhdpi/img_novel_info_none.png
  app/src/main/res/drawable/bg_dialog_remove_100_radius_8dp.xml
  app/src/main/res/drawable/bg_feed_popup.xml
  app/src/main/res/drawable/bg_floating_write_button.xml
  app/src/main/res/drawable/ic_report_check.xml
  app/src/main/res/drawable/img_novel_info_none.png
  app/src/main/res/layout/dialog_remove_popup_menu.xml
  app/src/main/res/layout/dialog_report_done_popup_menu.xml
  app/src/main/res/layout/dialog_report_popup_menu.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_feed_loading.xml
  app/src/main/res/layout/menu_feed_popup.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  settings.gradle.kts
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#141 feat: 작품평가 뷰 API 구현
  app/src/main/java/com/teamwss/websoso/data/mapper/UserNovelMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelRatingEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserNovelApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/NovelRatingRequestDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelRatingResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelRatingRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserNovelRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelRatingMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingDateBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/util/RatingDateManager.kt
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/activity_novel_rating.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#151 build: 중복 코드로 인한 빌드 에러 해결
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
Labels: 🏹 궁사 명지, 🚧 [BUILD]

#112 feat: 상세 탐색 키워드 어댑터 연결
  app/src/main/java/com/teamwss/websoso/data/mapper/KeywordMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/KeywordsEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/KeywordsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeKeywordRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/model/DetailExploreKeywordModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/model/DetailExploreKeywordUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/DetailExploreMapper.kt
  app/src/main/res/layout/dialog_detail_explore.xml
  app/src/main/res/layout/fragment_detail_explore_keyword.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#132 feat: 작품상세 뷰 API 연결
  app/build.gradle.kts
  app/src/main/java/com/teamwss/websoso/data/di/ApiModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelDetailMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelInfoMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/UserNovelMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelRatingEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/FakeApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserNovelApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/NovelRatingRequestDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelDetailResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelRatingResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/DefaultFeedRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelDetailRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelInfoRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelRatingRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/NovelRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserNovelRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelDetailMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelInfoMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelRatingMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/adapter/NovelDetailPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/Category.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/ReadStatus.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingDateBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/util/RatingDateManager.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
  app/src/main/res/color/bg_novel_detail_read_status_selector.xml
  app/src/main/res/drawable/bg_novel_detail_interest_selector.xml
  app/src/main/res/drawable/ic_novel_detail_interest_selector.xml
  app/src/main/res/drawable/ic_novel_detail_watching_selector.xml
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/activity_novel_rating.xml
  app/src/main/res/layout/fragment_novel_info.xml
  app/src/main/res/layout/menu_novel_detail_popup.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#149 feat: 마이페이지 내 서재 장르취향 ui 구현
  app/src/main/java/com/teamwss/websoso/data/model/GenrePreferenceEntity.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/adapter/MyPageViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/adapter/RestGenrePreferenceAdapter.kt
  app/src/main/java/com/teamwss/websoso/util/ViewExtensions.kt
  app/src/main/res/drawable/ic_my_library_genre_test.xml
  app/src/main/res/drawable/ic_my_library_lower_path.xml
  app/src/main/res/drawable/ic_my_library_upper_path.xml
  app/src/main/res/layout/fragment_my_library.xml
  app/src/main/res/layout/item_rest_genre.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#155 feat: notice api 연결
  app/src/main/java/com/teamwss/websoso/data/di/ApiModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/NoticeMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/NoticesEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/NoticeApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NoticesResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/NoticeRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NoticeMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/notice/NoticeActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/notice/NoticeAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/notice/NoticeViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/notice/NoticeViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/notice/model/NoticeModel.kt
  app/src/main/java/com/teamwss/websoso/ui/notice/model/NoticeUiState.kt
  app/src/main/res/drawable/ic_home_alert.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/item_notice.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#154 feat: Home Ui 구현
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/first/model/OnboardingFirstUiModel.kt
  app/src/main/res/drawable/bg_home_primary100_radius_8dp.xml
  app/src/main/res/drawable/bg_home_secondary100_radius_8dp.xml
  app/src/main/res/drawable/bg_home_white_stroke_gray_70_radius_14dp.xml
  app/src/main/res/drawable/bg_onboarding_white_stroke_gray_70_radius_12dp.xml
  app/src/main/res/drawable/bg_onboarding_white_stroke_primary_100_radius_12dp.xml
  app/src/main/res/drawable/bg_onboarding_white_stroke_secondary_100_radius_12dp.xml
  app/src/main/res/drawable/bg_popular_novel_gradient_radius_14dp.xml
  app/src/main/res/drawable/bg_popular_novel_white_botttom_radius_14dp.xml
  app/src/main/res/drawable/bg_user_interest_gray_20_bottom_radius_14dp.xml
  app/src/main/res/drawable/bg_user_interest_gray_50_radius_4dp.xml
  app/src/main/res/drawable/bg_user_interest_white_radius_14dp.xml
  app/src/main/res/drawable/ic_home_comment.xml
  app/src/main/res/drawable/ic_home_heart.xml
  app/src/main/res/drawable/ic_home_hot.xml
  app/src/main/res/drawable/ic_home_info_circle.xml
  app/src/main/res/drawable/ic_home_like.xml
  app/src/main/res/drawable/ic_home_logo.xml
  app/src/main/res/drawable/ic_home_notification.xml
  app/src/main/res/drawable/ic_home_star_orange.xml
  app/src/main/res/drawable/ic_popular_feed_comment.xml
  app/src/main/res/drawable/ic_popular_feed_like.xml
  app/src/main/res/drawable/ic_popular_novel_best.xml
  app/src/main/res/drawable/ic_popular_novel_commas_finished.xml
  app/src/main/res/drawable/ic_popular_novel_commas_started.xml
  app/src/main/res/drawable/ic_taste_novel_interest.xml
  app/src/main/res/drawable/ic_taste_novel_rating.xml
  app/src/main/res/drawable/ic_user_interest_feed_star_black.xml
  app/src/main/res/drawable/selector_onboarding_first_duplication_check_button_background.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_popular_feed.xml
  app/src/main/res/layout/item_popular_novel.xml
  app/src/main/res/layout/item_taste_novel.xml
  app/src/main/res/layout/item_user_interest_feed.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/typography.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#158 feat: 로그인 페이지 디자인 변경 사항 대응, 디테일 수정
  app/src/main/java/com/teamwss/websoso/data/mapper/NoticeMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/login/LoginActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/login/LoginViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NoticeMapper.kt
  app/src/main/res/drawable-xhdpi/img_login_1.png
  app/src/main/res/drawable-xhdpi/img_login_2.png
  app/src/main/res/drawable-xhdpi/img_login_3.png
  app/src/main/res/drawable-xhdpi/img_login_4.png
  app/src/main/res/drawable-xxhdpi/img_login_1.png
  app/src/main/res/drawable-xxhdpi/img_login_2.png
  app/src/main/res/drawable-xxhdpi/img_login_3.png
  app/src/main/res/drawable-xxhdpi/img_login_4.png
  app/src/main/res/drawable-xxxhdpi/img_login_1.png
  app/src/main/res/drawable-xxxhdpi/img_login_2.png
  app/src/main/res/drawable-xxxhdpi/img_login_3.png
  app/src/main/res/drawable-xxxhdpi/img_login_4.png
  app/src/main/res/drawable/bg_login_white_radius_14dp_stroke_primary100_1dp.xml
  app/src/main/res/drawable/img_login_1.png
  app/src/main/res/drawable/img_login_2.png
  app/src/main/res/drawable/img_login_3.png
  app/src/main/res/drawable/img_login_4.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_home.xml
Labels: 🍯 [FEAT], 🔨 [FIX], 🗡️ 대장군 재원

#156 feat: 피드 상세보기 UI 구현
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/res/drawable/bg_feed_detail_gray_50_radius_14dp.xml
  app/src/main/res/drawable/btn_comment_register.xml
  app/src/main/res/drawable/btn_explore_back.xml
  app/src/main/res/layout/activity_feed_detail.xml
  app/src/main/res/layout/item_feed_detail_comment.xml
  app/src/main/res/layout/item_feed_detail_header.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#160 feat: 피드 상세보기 뷰 멀티뷰타입 어댑터 구현
  app/src/main/java/com/teamwss/websoso/ui/feed/adapter/FeedType.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailCommentViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailContentViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailType.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/FeedDetailModel.kt
  app/src/main/res/layout/activity_feed_detail.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#153 feat: 일반 검색 결과 스크롤 영역 수정
  app/build.gradle.kts
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreHeaderViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreItemType.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/model/NormalExploreUiState.kt
  app/src/main/res/layout/activity_normal_explore.xml
  app/src/main/res/layout/item_normal_explore_header.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#164 feat: 피드 상세보기 뷰 데이터 레이어 구현 및 연결
  app/src/main/java/com/teamwss/websoso/data/di/ApiModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/RepositoryModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/ServiceModule.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/FeedMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/CommentEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/CommentsEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/FeedApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/CommentResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/CommentsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/DefaultFeedRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedScrollListener.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailCommentViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailContentViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailType.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/CommentModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/FeedDetailModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/FeedDetailUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/FeedMapper.kt
  app/src/main/res/layout/item_feed_detail_comment.xml
  app/src/main/res/layout/item_feed_detail_header.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#174 feat: 마이페이지 환경 설정 ui 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/setting/SettingActivity.kt
  app/src/main/res/drawable/btn_setting_back.xml
  app/src/main/res/drawable/btn_setting_right.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#173 feat: 상세 탐색 디자인 상세 구현
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultViewModel.kt
  app/src/main/res/layout/activity_detail_explore_result.xml
  app/src/main/res/layout/fragment_detail_explore_keyword.xml
  app/src/main/res/layout/item_detail_explore_result.xml
  app/src/main/res/layout/item_detail_explore_result_header.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#182 feat: 프로필 비공개 여부 ui 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureActivity.kt
  app/src/main/res/drawable/btn_profile_disclosure_private.xml
  app/src/main/res/drawable/btn_profile_disclosure_public.xml
  app/src/main/res/layout/activity_profile_disclosure.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#170 feat: 닉네임 변경 반영
  README.md
Labels: 🍯 [FEAT], 🔮 법사 준서

#184 feat: 온보딩 바텀시트 BirthYear Picker 구현
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingBirthYearBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/second/OnboardingSecondFragment.kt
  app/src/main/res/drawable/bg_onboarding_dialog_bottom_sheet_primary_100_radius_12dp.xml
  app/src/main/res/drawable/bg_onboarding_dialog_bottom_sheet_primary_20_radius_12dp.xml
  app/src/main/res/drawable/bg_onboarding_dialog_bottom_sheet_white_radius_top_12dp.xml
  app/src/main/res/layout/dialog_onboarding_birth_year.xml
  app/src/main/res/layout/fragment_onboarding_first.xml
  app/src/main/res/layout/fragment_onboarding_second.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#176 feat: 계정 정보 ui 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/accountInfo/AccountInfoActivity.kt
  app/src/main/res/layout/activity_account_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#189 feat: 온보딩 두 번째 화면 UiState 로직 구현
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/first/OnboardingFirstFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/model/OnboardingPage.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/model/UserModel.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/second/OnboardingSecondFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/second/model/OnboardingSecondUiState.kt
  app/src/main/res/layout/fragment_onboarding_first.xml
  app/src/main/res/layout/fragment_onboarding_second.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원, 🚨[Emergency]

#180 feat: 차단유저 목록 ui 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/blockUsers/BlockUsersActivity.kt
  app/src/main/res/drawable/bg_block_users_gray50_radius_20dp.xml
  app/src/main/res/drawable/img_block_users_avatar_test.png
  app/src/main/res/layout/activity_block_users.xml
  app/src/main/res/layout/item_block_user.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#172 feat: 내 서재 작품취향 UI 구현
  app/src/main/java/com/teamwss/websoso/data/model/NovelPreferenceEntity.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeUserRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/model/AttrativePoints.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryViewModel.kt
  app/src/main/res/drawable/bg_my_library_gray50_radius_12dp.xml
  app/src/main/res/layout/fragment_my_library.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#193 feat: 성별/나이 변경 ui 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/accountInfo/AccountInfoActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/changeGenderAndAge/ChangeBirthYearBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/changeGenderAndAge/ChangeGenderAndAgeActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/second/OnboardingSecondFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/setting/SettingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/setting/SettingClickListener.kt
  app/src/main/res/layout/activity_change_gender_and_age.xml
  app/src/main/res/layout/activity_setting.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#190 feat: 소소픽 API 연결
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/SosoPicksResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/NovelRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreViewModel.kt
Labels: 🍯 [FEAT], 🏹 궁사 명지

#195 feat: 온보딩 장르 선택 로직 구현
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/model/UserModel.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/third/OnboardingThirdFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/third/adapter/GenreAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/third/adapter/GenreViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/third/model/Genre.kt
  app/src/main/res/drawable/bg_onboarding_oval_gray50.xml
  app/src/main/res/drawable/ic_onboarding_bl.xml
  app/src/main/res/drawable/ic_onboarding_drama.xml
  app/src/main/res/drawable/ic_onboarding_fantasy.xml
  app/src/main/res/drawable/ic_onboarding_item_checked.xml
  app/src/main/res/drawable/ic_onboarding_light_novel.xml
  app/src/main/res/drawable/ic_onboarding_modern_fantasy.xml
  app/src/main/res/drawable/ic_onboarding_mystery.xml
  app/src/main/res/drawable/ic_onboarding_romance.xml
  app/src/main/res/drawable/ic_onboarding_romance_fantasy.xml
  app/src/main/res/drawable/ic_onboarding_wuxia.xml
  app/src/main/res/layout/fragment_onboarding_first.xml
  app/src/main/res/layout/fragment_onboarding_third.xml
  app/src/main/res/layout/item_onboarding_genre.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#200 feat: 계정정보 뷰 내 이메일 명시 API 연결
  app/src/main/java/com/teamwss/websoso/data/di/ApiModule.kt
  app/src/main/java/com/teamwss/websoso/data/di/RepositoryModule.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserEmailEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserEmailResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/accountInfo/AccountInfoActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/accountInfo/AccountInfoViewModel.kt
  app/src/main/res/layout/activity_account_info.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#201 feat: 차단유저 목록 recyclerView 어댑터 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/accountInfo/AccountInfoActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/blockUsers/BlockUsersActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/BlockedUsersActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/BlockedUsersViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/adapter/BlockedUsersAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/adapter/BlockedUsersViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/model/BlockedUsersModel.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/model/BlockedUsersUiState.kt
  app/src/main/res/drawable/bg_blocked_users_gray50_radius_20dp.xml
  app/src/main/res/drawable/img_blocked_users_avatar_test.png
  app/src/main/res/layout/activity_account_info.xml
  app/src/main/res/layout/activity_blocked_users.xml
  app/src/main/res/layout/item_blocked_user.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#206 feat: 유저 등록 작품 수 조회 api 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserNovelStatsEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserNovelStatsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/accountInfo/AccountInfoActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/WithdrawMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/withDraw/WithDrawFirstActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/first/WithdrawFirstActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/first/WithdrawFirstViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/first/model/UserNovelStatsModel.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/first/model/WithdrawFirstUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/second/WithdrawSecondActivity.kt
  app/src/main/res/layout/activity_withdraw_first.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#204 feat: 차단유저 목록 api 연결
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/BlockedUsersEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/BlockedUsersResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/BlockedUsersActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/BlockedUsersViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/adapter/BlockedUsersAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/adapter/BlockedUsersViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/model/BlockedUsersModel.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/model/BlockedUsersUiState.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
  app/src/main/res/layout/activity_blocked_users.xml
  app/src/main/res/layout/item_blocked_user.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#208 feat: 유저 프로필 공개 여부 api 연결 및 로직 구현
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserProfileStatusEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/UserProfileStatusRequestDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserProfileStatusResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/model/ProfileDisclosureUiState.kt
  app/src/main/res/color/bg_profile_disclosure_text_selector.xml
  app/src/main/res/drawable/btn_comment_register.xml
  app/src/main/res/drawable/img_account_info_check_selected.xml
  app/src/main/res/drawable/img_account_info_check_unselected.xml
  app/src/main/res/layout/activity_feed_detail.xml
  app/src/main/res/layout/activity_profile_disclosure.xml
  app/src/main/res/layout/activity_withdraw_second.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#188 feat: 프로필 편집 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/Genres.kt
  app/src/main/res/color/bg_profile_edit_chip_background_selector.xml
  app/src/main/res/color/bg_profile_edit_chip_stroke_selector.xml
  app/src/main/res/color/bg_profile_edit_chip_text_selector.xml
  app/src/main/res/drawable/bg_profile_edit_gray_50_radius_12dp.xml
  app/src/main/res/drawable/bg_profile_edit_gray_70_radius_12dp.xml
  app/src/main/res/drawable/ic_profile_edit_add.xml
  app/src/main/res/drawable/ic_profile_edit_back.xml
  app/src/main/res/drawable/ic_profile_edit_clear.xml
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#210 feat: 홈 오늘의 인기작 API 연결 및 구현
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/PopularNovelsEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/PopularNovelsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/NovelRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/PopularNovelsAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/PopularNovelsViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/model/HomeUiState.kt
  app/src/main/res/drawable/bg_popular_novel_fcf8f6_bottom_radius_14dp.xml
  app/src/main/res/drawable/ic_popular_novel_null_avatar.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_popular_novel.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#183 feat: 키워드 검색기능 구현
  app/src/main/java/com/teamwss/websoso/ui/common/customView/WebsosoSearchEditText.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/adapter/NovelRatingKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiState.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
  app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
  app/src/main/res/drawable/bg_common_search_selector.xml
  app/src/main/res/drawable/bg_novel_rating_primary_50_radius_14dp.xml
  app/src/main/res/drawable/ic_common_search.xml
  app/src/main/res/drawable/ic_common_search_clear.xml
  app/src/main/res/drawable/ic_novel_rating_keyword_empty.xml
  app/src/main/res/layout/activity_novel_rating.xml
  app/src/main/res/layout/dialog_novel_rating_keyword.xml
  app/src/main/res/layout/fragment_detail_explore_keyword.xml
  app/src/main/res/layout/layout_search.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#171 feat: 작품평가 뷰 키워드 세부기능 구현
  app/src/main/java/com/teamwss/websoso/data/di/ApiModule.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/KeywordMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/UserNovelMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/CategoriesEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelRatingEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelRatingKeywordCategoryEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelRatingKeywordEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/KeywordApi.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeKeywordRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/KeywordRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/accountInfo/AccountInfoActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/BlockedUsersActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/ChangeUserInfoActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/common/base/BindingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/common/customView/WebsosoSearchEditText.kt
  app/src/main/java/com/teamwss/websoso/ui/common/model/CategoriesModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/model/DetailExploreKeywordUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/DetailExploreMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/KeywordMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelRatingMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/adapter/NovelRatingKeywordAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/adapter/NovelRatingKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/setting/SettingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/first/WithdrawFirstActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/second/WithdrawSecondActivity.kt
  app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
  app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
  app/src/main/res/drawable/bg_common_search_selector.xml
  app/src/main/res/drawable/bg_novel_rating_primary_50_radius_14dp.xml
  app/src/main/res/drawable/ic_common_search.xml
  app/src/main/res/drawable/ic_common_search_clear.xml
  app/src/main/res/drawable/ic_novel_rating_keyword_empty.xml
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/activity_novel_rating.xml
  app/src/main/res/layout/activity_withdraw_second.xml
  app/src/main/res/layout/dialog_novel_rating_keyword.xml
  app/src/main/res/layout/fragment_detail_explore_keyword.xml
  app/src/main/res/layout/item_common_keyword.xml
  app/src/main/res/layout/layout_search.xml
  app/src/main/res/layout/menu_novel_detail_popup.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#221 feat: 계정정보 관련 수정된 api 및 ui 반영
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserEmailEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserInfoEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserUpdateInfoEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/UserInfoRequestDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserInfoResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/accountInfo/AccountInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/ChangeBirthYearBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/ChangeUserInfoActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/ChangeUserInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/model/ChangeUserInfoUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/model/Gender.kt
  app/src/main/res/layout/activity_change_user_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#222 feat: 홈 화면 지금 뜨는 수다글 API 연결 및 구현
  app/src/main/java/com/teamwss/websoso/data/mapper/FeedMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/PopularFeedsEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/FeedApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/PopularFeedsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/PopularNovelsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/PopularFeedsAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/PopularFeedsViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/model/HomeUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/second/model/OnboardingSecondUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/third/OnboardingThirdFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/third/adapter/GenreAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_onboarding_second.xml
  app/src/main/res/layout/item_popular_feed.xml
  app/src/main/res/layout/item_popular_feed_slot.xml
  app/src/main/res/layout/item_popular_novel.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#218 feat: 작품평가 툴팁 추가
  app/build.gradle.kts
  app/src/main/java/com/teamwss/websoso/common/ui/custom/WebsosoChip.kt
  app/src/main/java/com/teamwss/websoso/common/util/ExtentionFuction.kt
  app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserPreferencesRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/adapter/NovelRatingKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/ReadStatus.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/util/RatingDateManager.kt
  app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
  app/src/main/res/drawable-xhdpi/bg_novel_detail_tooltip_frame.png
  app/src/main/res/drawable-xhdpi/ic_novel_detail_genre_frame.png
  app/src/main/res/drawable-xhdpi/ic_novel_detail_tooltip.png
  app/src/main/res/drawable-xxhdpi/bg_novel_detail_tooltip_frame.png
  app/src/main/res/drawable-xxhdpi/ic_novel_detail_genre_frame.png
  app/src/main/res/drawable-xxhdpi/ic_novel_detail_tooltip.png
  app/src/main/res/drawable/bg_novel_detail_primary_50_radius_14dp.xml
  app/src/main/res/drawable/bg_novel_detail_tooltip_frame.png
  app/src/main/res/drawable/ic_novel_detail_genre_frame.png
  app/src/main/res/drawable/ic_novel_detail_tooltip.png
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/item_novel_detail_tooltip.xml
  app/src/main/res/layout/menu_novel_detail_popup.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#229 refactor: 상세 탐색 프래그먼트 생성 로직 수정
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreDialogBottomSheet.kt
Labels: 🍯 [FEAT], 🏹 궁사 명지

#219 feat: 회원탈퇴 로직 구현
  app/src/main/java/com/teamwss/websoso/ui/withdraw/second/WithdrawClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/second/WithdrawSecondActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/withdraw/second/WithdrawSecondViewModel.kt
  app/src/main/res/drawable/btn_withdraw_check_selector.xml
  app/src/main/res/drawable/img_withdraw_second_check_button_selector.xml
  app/src/main/res/layout/activity_withdraw_second.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#231 feat: 홈 화면 {nickname}님의 관심글 API 연결 및 구현
  app/src/main/java/com/teamwss/websoso/data/mapper/FeedMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserInterestFeedsEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/FeedApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserInterestFeedsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/common/dialog/LoginRequestDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/login/LoginActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/PopularFeedsViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/UserInterestFeedAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/UserInterestFeedViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/model/HomeUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/splash/SplashActivity.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_popular_feed_slot.xml
  app/src/main/res/layout/item_user_interest_feed.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#234 feat: 범용적으로 사용할 수 있는 커스텀 스낵바 구현
  app/src/main/java/com/teamwss/websoso/common/ui/custom/WebsosoCustomSnackBar.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/UserUpdateInfoEntity.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/BlockedUsersActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/BlockedUsersViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureViewModel.kt
  app/src/main/res/drawable/bg_snack_bar_gray_cc_394258_radius_4dp.xml
  app/src/main/res/drawable/ic_blocked_user_snack_bar.xml
  app/src/main/res/layout/custom_snack_bar.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#248 refactor: 피드 상세보기 뷰 api 연결 수정
  app/src/main/java/com/teamwss/websoso/data/mapper/FeedMapper.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/FeedApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/CommentResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/CommentsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/FeedDetailResponseDto.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailContentViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailType.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/CommentModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/FeedDetailModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedItemClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedScrollListener.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/adapter/FeedAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/adapter/FeedLoadingViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/adapter/FeedType.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/adapter/FeedViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/dialog/FeedRemoveDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/dialog/FeedReportDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/dialog/FeedReportDoneDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/model/Category.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/model/CategoryModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/model/FeedModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/model/FeedUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/FeedMapper.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_feed_detail_header.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#224 feat: 내 활동 ui 구현
  app/src/main/java/com/teamwss/websoso/data/model/MyActivitiesEntity.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeMyActivityRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/ActivityMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/adapter/MyActivityAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/adapter/MyActivityViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/model/ActivityModel.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/model/Genres.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/model/AttrativePoints.kt
  app/src/main/res/drawable/bg_my_activity_white_radius_8dp_stroke_primary100.xml
  app/src/main/res/drawable/bg_my_page_gray70.xml
  app/src/main/res/drawable/btn_my_activity_novel_info.xml
  app/src/main/res/layout/fragment_my_activity.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_my_activity.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#252 feat: 앱 아이콘 등록
  app/src/main/AndroidManifest.xml
  app/src/main/ic_wss_logo-playstore.png
  app/src/main/res/drawable/ic_wss_logo_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_wss_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_wss_logo_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-hdpi/ic_wss_logo.webp
  app/src/main/res/mipmap-hdpi/ic_wss_logo_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_wss_logo.webp
  app/src/main/res/mipmap-mdpi/ic_wss_logo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_wss_logo.webp
  app/src/main/res/mipmap-xhdpi/ic_wss_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_wss_logo.webp
  app/src/main/res/mipmap-xxhdpi/ic_wss_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_wss_logo.webp
  app/src/main/res/mipmap-xxxhdpi/ic_wss_logo_round.webp
  app/src/main/res/values/ic_wss_logo_background.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#254 feat: 홈 뷰 "이 웹소설은 어때요" api 연결 및 구현
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/RecommendedNovelsByUserTasteEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/RecommendedNovelsByUserTasteResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/NovelRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/RecommendedNovelsByUserTasteAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/adpater/RecommendedNovelsByUserTasteViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/model/HomeUiState.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_recommended_novel_by_user_taste.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#226 feat: 내 활동 디테일 ui 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/data/repository/UserFeedRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/adapter/MyPageViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/adapter/MyActivityAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/adapter/MyActivityViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/ActivityModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/Genres.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/adapter/RestGenrePreferenceAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/model/AttrativePoints.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/ActivityMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/MyActivityDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/MyActivityDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/adapter/MyActivityDetailAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/adapter/MyActivityDetailViewHolder.kt
  app/src/main/res/layout/activity_my_activity_detail.xml
  app/src/main/res/layout/fragment_my_library.xml
  app/src/main/res/layout/item_my_activity.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#258 fix: 툴팁 정보 저장 오류 해결
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
Labels: 🔨 [FIX], 🔮 법사 준서, 🚨[Emergency]

#256 feat: 피드 상세보기 뷰 댓글 기능 구현
  app/src/main/java/com/teamwss/websoso/data/mapper/FeedMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/CommentEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/FeedApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/CommentRequestDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/CommentResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/CommentClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailCommentViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailContentViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/CommentModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/dialog/FeedRemoveDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/dialog/FeedReportDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/dialog/FeedReportDoneDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/FeedMapper.kt
  app/src/main/res/layout/activity_feed_detail.xml
  app/src/main/res/layout/dialog_remove_popup_menu.xml
  app/src/main/res/layout/dialog_report_done_popup_menu.xml
  app/src/main/res/layout/dialog_report_popup_menu.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_feed_detail_comment.xml
  app/src/main/res/layout/item_feed_detail_header.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#253 feat: 일반 검색 api 연결
  app/src/main/java/com/teamwss/websoso/common/util/InfiniteScrollListener.kt
  app/src/main/java/com/teamwss/websoso/data/di/RepositoryModule.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/ExploreResultResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeSosoPickRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/NovelRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/domain/model/NormalExploreResult.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetNormalExploreResultsUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/changeUserInfo/ChangeBirthYearBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/login/LoginActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreHeaderViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreItemType.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreLoadingViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/model/NormalExploreModel.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/model/NormalExploreUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/notice/NoticeActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingActivity.kt
  app/src/main/res/layout/item_normal_explore.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#260 feat: 다른유저페이지 프로필 및 스티키헤더 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/adapter/OtherUserPageViewPagerAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
  app/src/main/res/drawable/ic_other_user_page_kebab.xml
  app/src/main/res/layout/activity_other_user_page.xml
  app/src/main/res/layout/fragment_other_user_activity.xml
  app/src/main/res/layout/fragment_other_user_library.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#262 feat: 마이페이지 프로필 및 내 서재 api 연결
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/GenrePreferenceEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/MyProfileEntity.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelPreferenceEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/GenrePreferenceResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/MyProfileResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelPreferenceResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeUserRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/Genres.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageActivity.kt
  app/src/main/res/layout/fragment_my_library.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_rest_genre.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#263 feat: 피드 상세보기 뷰 기능 구현
  app/src/main/java/com/teamwss/websoso/data/model/MyActivitiesEntity.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailContentViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/adapter/FeedDetailType.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/model/FeedDetailUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/adapter/MyActivityAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/model/ActivityModel.kt
  app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/MyActivityDetailViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/adapter/MyActivityDetailAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/adapter/MyActivityDetailViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreLoadingViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/OtherUserPageActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureViewModel.kt
  app/src/main/res/layout/activity_feed_detail.xml
  app/src/main/res/layout/item_feed_detail_header.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#265 feat: 상세 탐색 로직 구현
  app/src/main/java/com/teamwss/websoso/data/repository/FakeKeywordRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreDialogBottomSheet.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/model/SeriesStatus.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
  app/src/main/res/layout/fragment_detail_explore_info.xml
  app/src/main/res/layout/fragment_detail_explore_keyword.xml
  app/src/main/res/layout/item_common_keyword.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지, 🚨[Emergency]

#269 feat: 상세 탐색 키워드 검색 로직 구현
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreClickListener.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/model/DetailExploreKeywordUiState.kt
  app/src/main/res/layout/fragment_detail_explore_keyword.xml
  app/src/main/res/layout/layout_search.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#271 feat: 상세 탐색 검색 결과 api 연결
  app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/NovelRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/domain/model/ExploreResult.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetDetailExploreResultUseCase.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetNormalExploreResultUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/model/Genre.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/adapter/DetailExploreLoadingViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/adapter/DetailExploreResultAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/adapter/DetailExploreResultHeaderViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/adapter/DetailExploreResultItemType.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/adapter/DetailExploreResultViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/model/DetailExploreResultUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreItemType.kt
  app/src/main/res/layout/activity_detail_explore_result.xml
  app/src/main/res/layout/item_detail_explore_result.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#267 feat: 피드 생성하기 뷰 ui 구현 및 데이터바인딩 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/model/CreateFeedCategory.kt
  app/src/main/res/color/bg_create_feed_done_button_selector.xml
  app/src/main/res/drawable/bg_create_feed_edit_text_radius_14dp.xml
  app/src/main/res/drawable/bg_create_feed_toggle.xml
  app/src/main/res/drawable/bg_create_feed_toggle_off.xml
  app/src/main/res/drawable/bg_create_feed_toggle_on.xml
  app/src/main/res/drawable/bg_create_feed_toggle_thumb.xml
  app/src/main/res/drawable/ic_star_essential.xml
  app/src/main/res/layout/activity_create_feed.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#272 feat: 닉네임, 성별, 출생년도, 취향 등록 API 연결
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/UserProfileRequestDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/second/OnboardingSecondFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/third/OnboardingThirdFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/welcome/WelcomeActivity.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_welcome.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#255 feat: 캐릭터 선택 구현
  app/src/main/java/com/teamwss/websoso/data/di/ApiModule.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/AvatarMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/AvatarEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/AvatarApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/AvatarsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/AvatarRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/AvatarMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditCharacterBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/adapter/AvatarChangeAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/adapter/AvatarChangeViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/Avatar.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/AvatarChangeUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/AvatarChangeUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/ProfileEditUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/ProfileEditUiState.kt
  app/src/main/res/color/bg_profile_edit_nickname_finish_selector.xml
  app/src/main/res/drawable/bg_profile_edit_oval_primary_100.xml
  app/src/main/res/drawable/bg_profile_edit_primary_100_radius_14dp.xml
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/layout/dialog_avatar_change.xml
  app/src/main/res/layout/dialog_profile_edit_character.xml
  app/src/main/res/layout/item_profile_edit_avatar.xml
  app/src/main/res/raw/lottie_regressor_0.json
  app/src/main/res/raw/lottie_regressor_1.json
  app/src/main/res/raw/lottie_sosocat_0.json
  app/src/main/res/raw/lottie_sosocat_1.json
  app/src/main/res/raw/lottie_villainess_0.json
  app/src/main/res/raw/lottie_villainess_1.json
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#230 feat: 프로필 수정 API 연결
  app/build.gradle.kts
  app/src/main/java/com/teamwss/websoso/common/util/ExtentionFuction.kt
  app/src/main/java/com/teamwss/websoso/data/di/ApiModule.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/AvatarMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/FeedMapper.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/AvatarEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/AvatarApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/UserProfileEditRequestDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/AvatarsResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/UserNicknameValidityResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/AvatarRepository.kt
  app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/model/NicknameValidationResult.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/CheckNicknameValidityUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/AvatarMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/adapter/AvatarChangeAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/adapter/AvatarChangeViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/Avatar.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/AvatarChangeUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/AvatarChangeUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/Genre.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/Genres.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/ProfileEditUiModel.kt
  app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/ProfileEditUiState.kt
  app/src/main/res/color/bg_profile_edit_nickname_finish_selector.xml
  app/src/main/res/color/bg_profile_edit_nickname_result_selector.xml
  app/src/main/res/drawable/bg_profile_edit_introduction_selector.xml
  app/src/main/res/drawable/bg_profile_edit_oval_primary_100.xml
  app/src/main/res/drawable/bg_profile_edit_primary_100_radius_14dp.xml
  app/src/main/res/drawable/bg_profile_edit_primary_50_radius_12dp.xml
  app/src/main/res/drawable/bg_profile_edit_white_stroke_gray_70_radius_12dp.xml
  app/src/main/res/drawable/bg_profile_edit_white_stroke_primary_100_radius_12dp.xml
  app/src/main/res/drawable/bg_profile_edit_white_stroke_secondary_100_radius_12dp.xml
  app/src/main/res/drawable/ic_profile_edit_clear_error.xml
  app/src/main/res/drawable/ic_profile_edit_error_selector.xml
  app/src/main/res/drawable/ic_profile_edit_nickname_valid.xml
  app/src/main/res/layout/activity_create_feed.xml
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/layout/dialog_avatar_change.xml
  app/src/main/res/layout/item_profile_edit_avatar.xml
  app/src/main/res/raw/lottie_regressor_0.json
  app/src/main/res/raw/lottie_regressor_1.json
  app/src/main/res/raw/lottie_sosocat_0.json
  app/src/main/res/raw/lottie_sosocat_1.json
  app/src/main/res/raw/lottie_villainess_0.json
  app/src/main/res/raw/lottie_villainess_1.json
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#261 feat: 스낵바 및 다이알로그 추가
  app/src/main/java/com/teamwss/websoso/common/ui/custom/WebsosoCustomToast.kt
  app/src/main/java/com/teamwss/websoso/common/util/ExtentionFuction.kt
  app/src/main/java/com/teamwss/websoso/ui/blockedUsers/BlockedUsersActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelAlertDialogFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelAlertModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingDateBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingKeywordBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/adapter/NovelRatingKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiModel.kt
  app/src/main/res/drawable/bg_novel_detail_cover_background.xml
  app/src/main/res/drawable/bg_novel_detail_secondary_100_radius_8dp.xml
  app/src/main/res/drawable/ic_novel_detail_check.xml
  app/src/main/res/drawable/ic_novel_rating_alert.xml
  app/src/main/res/layout/activity_novel_detail.xml
  app/src/main/res/layout/activity_novel_rating.xml
  app/src/main/res/layout/custom_snack_bar.xml
  app/src/main/res/layout/dialog_novel_alert.xml
  app/src/main/res/layout/dialog_novel_detail_remove.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#279 feat: 피드 상세보기 뷰 작품 연결하기 기능 구현
  app/src/main/java/com/teamwss/websoso/common/ui/custom/WebsosoSearchEditText.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedSearchNovelBottomSheetDialog.kt
  app/src/main/res/drawable/btn_feed_novel_info.xml
  app/src/main/res/layout/activity_create_feed.xml
  app/src/main/res/layout/dialog_create_feed_search_novel.xml
  app/src/main/res/layout/item_search_novel.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#277 feat: 닉네임 유효성 확인 api 적용
  app/src/main/java/com/teamwss/websoso/domain/usecase/ValidateNicknameUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/onboarding/first/OnboardingFirstFragment.kt
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_onboarding_first.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#266 feat: 작품상세 뷰 피드 기능 구현
  app/src/main/java/com/teamwss/websoso/common/ui/custom/WebsosoChip.kt
  app/src/main/java/com/teamwss/websoso/common/ui/custom/WebsosoCustomToast.kt
  app/src/main/java/com/teamwss/websoso/common/util/ExtentionFuction.kt
  app/src/main/java/com/teamwss/websoso/data/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/data/model/NovelFeedsEntity.kt
  app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/response/NovelFeedResponseDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/NovelRepository.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultInfoFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultKeywordFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/mapper/NovelMapper.kt
  app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/novelFeed/model/NovelFeedUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/novelRating/adapter/NovelRatingKeywordViewHolder.kt
  app/src/main/res/layout/fragment_novel_feed.xml
  app/src/main/res/layout/item_common_keyword.xml
  app/src/main/res/layout/item_detail_explore_result.xml
  app/src/main/res/layout/item_feed.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#282 feat: 작품 연결하기 기능 구현
  app/src/main/java/com/teamwss/websoso/data/remote/api/FeedApi.kt
  app/src/main/java/com/teamwss/websoso/data/remote/request/FeedRequestDto.kt
  app/src/main/java/com/teamwss/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/teamwss/websoso/domain/usecase/GetSearchedNovelsUseCase.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedSearchNovelBottomSheetDialog.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/CreateFeedViewModel.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/adapter/SearchNovelAdapter.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/adapter/SearchNovelItemType.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/adapter/SearchNovelLoadingViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/adapter/SearchedNovelViewHolder.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/model/CreateFeedCategory.kt
  app/src/main/java/com/teamwss/websoso/ui/createFeed/model/SearchNovelUiState.kt
  app/src/main/java/com/teamwss/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/teamwss/websoso/ui/normalExplore/model/NormalExploreModel.kt
  app/src/main/res/layout/activity_create_feed.xml
  app/src/main/res/layout/activity_normal_explore.xml
  app/src/main/res/layout/dialog_create_feed_search_novel.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_search_novel.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#287 feat: setupTranslucentOnStatusBar 제거, 스플래시 아이콘 제거
  app/src/main/java/com/teamwss/websoso/common/ui/base/BaseActivity.kt
  app/src/main/res/values/themes.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원
