Repository Team-WSS/WSS-Android, pull requests merged in 2025-04, with the labels that each got.

#623 feat: 수다 → 피드 UX라이팅 변경
  app/src/main/res/drawable-xhdpi/img_login_4.png
  app/src/main/res/drawable-xxhdpi/img_login_4.png
  app/src/main/res/drawable-xxxhdpi/img_login_4.png
  app/src/main/res/drawable/img_login_4.png
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#626 refactor: 프로젝트 Modularization 적용 (2) #622
  app/build.gradle.kts
  build-logic/.gitignore
  build-logic/build.gradle.kts
  build-logic/settings.gradle.kts
  build-logic/src/main/kotlin/com/into/websoso/buildConfigExtensions.kt
  build-logic/src/main/kotlin/com/into/websoso/manifestExtensions.kt
  build-logic/src/main/kotlin/com/into/websoso/projectExtensions.kt
  build-logic/src/main/kotlin/com/into/websoso/websosoDependenciesExtensions.kt
  build-logic/src/main/kotlin/websoso.android.application.gradle.kts
  build-logic/src/main/kotlin/websoso.android.compose.gradle.kts
  build-logic/src/main/kotlin/websoso.android.coroutines.gradle.kts
  build-logic/src/main/kotlin/websoso.android.feature.gradle.kts
  build-logic/src/main/kotlin/websoso.android.hilt.gradle.kts
  build-logic/src/main/kotlin/websoso.android.kotlin.gradle.kts
  build-logic/src/main/kotlin/websoso.android.library.gradle.kts
  build-logic/src/main/kotlin/websoso.dagger.gradle.kts
  build-logic/src/main/kotlin/websoso.jvm.kotlin.gradle.kts
  build-logic/src/main/kotlin/websoso.kotlin.coroutines.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🍯 [FEAT], ♻️ [REFACTOR], ⚖️ 재상 세훈, 🚧 [BUILD]

#638 feat: 의견 남기기 링크 변경
  app/src/main/res/values/deepLinks.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#639 feat: 프로필 비공개 여부 버튼 > 토글 버튼으로 수정
  app/src/main/java/com/into/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/into/websoso/data/model/UserProfileStatusEntity.kt
  app/src/main/java/com/into/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/into/websoso/ui/profileDisclosure/ProfileDisclosureActivity.kt
  app/src/main/java/com/into/websoso/ui/profileDisclosure/ProfileDisclosureViewModel.kt
  app/src/main/java/com/into/websoso/ui/profileDisclosure/model/ProfileDisclosureUiState.kt
  app/src/main/res/layout/activity_profile_disclosure.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#646 feat: 서재탭 QA 사항 적용
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#648 feat: 작품 문의하기 링크 변경
  app/src/main/java/com/into/websoso/ui/detailExploreResult/DetailExploreResultActivity.kt
  app/src/main/java/com/into/websoso/ui/normalExplore/NormalExploreActivity.kt
  app/src/main/res/values/deepLinks.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#655 release: 1.2.0 버전 업데이트(to develop)
  gradle/libs.versions.toml
Labels: 🚀 [RELEASE]

#664 refactor: network 코어 모듈 분리
  app/build.gradle.kts
  core/network/.gitignore
  core/network/build.gradle.kts
  core/network/consumer-rules.pro
  core/network/proguard-rules.pro
  core/network/src/main/AndroidManifest.xml
  core/network/src/main/java/com/into/websoso/core/network/di/NetworkModule.kt
  settings.gradle.kts
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈, 🚧 [BUILD]

#665 refactor: 소셜로그인 클라이언트 모듈 구현
  app/build.gradle.kts
  core/auth-kakao/.gitignore
  core/auth-kakao/build.gradle.kts
  core/auth-kakao/consumer-rules.pro
  core/auth-kakao/proguard-rules.pro
  core/auth-kakao/src/main/AndroidManifest.xml
  core/auth-kakao/src/main/java/com/into/websoso/core/auth_kakao/KakaoAuthClient.kt
  core/auth-kakao/src/main/java/com/into/websoso/core/auth_kakao/di/KakaoAuthModule.kt
  core/auth/.gitignore
  core/auth/build.gradle.kts
  core/auth/src/main/java/com/into/websoso/core/auth/AuthClient.kt
  core/auth/src/main/java/com/into/websoso/core/auth/AuthIdentifier.kt
  core/auth/src/main/java/com/into/websoso/core/auth/AuthToken.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🍯 [FEAT], ♻️ [REFACTOR], ⚖️ 재상 세훈, 🚧 [BUILD]
