Repository Team-WSS/WSS-Android, pull requests merged in 2025-05, with the labels that each got.

#644 feat: 피드작성 뷰 비공개 설정 API 추가
  app/src/main/java/com/into/websoso/data/remote/request/FeedRequestDto.kt
  app/src/main/java/com/into/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/into/websoso/ui/createFeed/CreateFeedViewModel.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/model/EditFeedModel.kt
  app/src/main/res/layout/activity_create_feed.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#667 feat: 피드 수정시 비공개 여부 반영
  app/src/main/java/com/into/websoso/data/mapper/FeedMapper.kt
  app/src/main/java/com/into/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/into/websoso/data/model/FeedEntity.kt
  app/src/main/java/com/into/websoso/data/model/UserFeedsEntity.kt
  app/src/main/java/com/into/websoso/data/remote/response/FeedDetailResponseDto.kt
  app/src/main/java/com/into/websoso/data/remote/response/FeedResponseDto.kt
  app/src/main/java/com/into/websoso/data/remote/response/UserFeedsResponseDto.kt
  app/src/main/java/com/into/websoso/domain/mapper/FeedMapper.kt
  app/src/main/java/com/into/websoso/domain/model/Feed.kt
  app/src/main/java/com/into/websoso/ui/activityDetail/ActivityDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/model/FeedDetailUiState.kt
  app/src/main/java/com/into/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/into/websoso/ui/main/feed/model/FeedModel.kt
  app/src/main/java/com/into/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/into/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/into/websoso/ui/main/myPage/myActivity/model/ActivitiesModel.kt
  app/src/main/java/com/into/websoso/ui/mapper/ActivityMapper.kt
  app/src/main/java/com/into/websoso/ui/mapper/FeedMapper.kt
  app/src/main/java/com/into/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/novelFeed/NovelFeedFragment.kt
Labels: 🍯 [FEAT]

#643 feat: 피드작성 뷰 UI 비공개 추가 및 디테일 변경
  app/src/main/java/com/into/websoso/data/mapper/FeedMapper.kt
  app/src/main/java/com/into/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/into/websoso/data/model/FeedEntity.kt
  app/src/main/java/com/into/websoso/data/model/UserFeedsEntity.kt
  app/src/main/java/com/into/websoso/data/remote/request/FeedRequestDto.kt
  app/src/main/java/com/into/websoso/data/remote/response/FeedDetailResponseDto.kt
  app/src/main/java/com/into/websoso/data/remote/response/FeedResponseDto.kt
  app/src/main/java/com/into/websoso/data/remote/response/UserFeedsResponseDto.kt
  app/src/main/java/com/into/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/into/websoso/domain/mapper/FeedMapper.kt
  app/src/main/java/com/into/websoso/domain/model/Feed.kt
  app/src/main/java/com/into/websoso/ui/activityDetail/ActivityDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/createFeed/CreateFeedViewModel.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/model/EditFeedModel.kt
  app/src/main/java/com/into/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/into/websoso/ui/main/feed/model/FeedModel.kt
  app/src/main/java/com/into/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
  app/src/main/java/com/into/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/into/websoso/ui/main/myPage/myActivity/model/ActivitiesModel.kt
  app/src/main/java/com/into/websoso/ui/mapper/ActivityMapper.kt
  app/src/main/java/com/into/websoso/ui/mapper/FeedMapper.kt
  app/src/main/java/com/into/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/novelFeed/NovelFeedFragment.kt
  app/src/main/res/drawable/bg_create_feed_toggle_off.xml
  app/src/main/res/drawable/bg_create_feed_toggle_on.xml
  app/src/main/res/drawable/bg_create_feed_toggle_thumb.xml
  app/src/main/res/drawable/bg_create_feed_white_radius_14dp_stroke_gray70_1dp.xml
  app/src/main/res/layout/activity_create_feed.xml
  core/resource/src/main/res/drawable/ic_create_novel_lock.xml
  core/resource/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#668 feat: 피드 목록 비공개 관련 UI 추가
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_feed_detail_header.xml
  app/src/main/res/layout/item_my_activity.xml
  core/resource/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#672 fix: 카카오 로그인 웹뷰 콜백되지 않는 현상 해결
  build-logic/src/main/kotlin/com/into/websoso/BuildConfigExtensions.kt
Labels: 🏹 궁사 명지, 🔨 [FIX], 🚨[Emergency]

#666 refactor: 로그인 뷰 Compose 마이그레이션 및 모듈 분리
  build-logic/src/main/kotlin/websoso.android.feature.gradle.kts
  core/common/.gitignore
  core/common/build.gradle.kts
  core/common/consumer-rules.pro
  core/common/proguard-rules.pro
  core/common/src/main/AndroidManifest.xml
  core/common/src/main/java/com/into/websoso/core/common/extensions/FlowExtensions.kt
  feature/signin/.gitignore
  feature/signin/build.gradle.kts
  feature/signin/consumer-rules.pro
  feature/signin/proguard-rules.pro
  feature/signin/src/main/AndroidManifest.xml
  feature/signin/src/main/java/com/into/websoso/feature/signin/SignInScreen.kt
  feature/signin/src/main/java/com/into/websoso/feature/signin/SignInViewModel.kt
  feature/signin/src/main/java/com/into/websoso/feature/signin/component/OnboardingDotsIndicator.kt
  feature/signin/src/main/java/com/into/websoso/feature/signin/component/OnboardingHorizontalPager.kt
  feature/signin/src/main/java/com/into/websoso/feature/signin/component/SignInButtons.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🍯 [FEAT], ♻️ [REFACTOR], ⚖️ 재상 세훈, 🚧 [BUILD]

#675 feat: Datastore 모듈 구현
  core/datastore/.gitignore
  core/datastore/build.gradle.kts
  core/datastore/consumer-rules.pro
  core/datastore/proguard-rules.pro
  core/datastore/src/main/AndroidManifest.xml
  core/datastore/src/main/java/com/into/websoso/core/datastore/datasource/gitkeep
  core/datastore/src/main/java/com/into/websoso/core/datastore/di/DataStoreModule.kt
  settings.gradle.kts
Labels: 🍯 [FEAT], ⚖️ 재상 세훈, 🚧 [BUILD]

#681 feat: 온보딩 개인정보처리방침 / 서비스 이용약관 링크 수정
  app/src/main/java/com/into/websoso/ui/termsAgreement/TermsAgreementDialogBottomSheet.kt
  core/resource/src/main/res/values/deepLinks.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#676 refactor: 토큰 Interceptor 및 Authenticator 구현
  app/build.gradle.kts
  app/src/main/java/com/into/websoso/WebsosoApp.kt
  app/src/main/java/com/into/websoso/core/common/util/navigator/WebsosoNavigator.kt
  app/src/main/java/com/into/websoso/core/common/util/sessionManager/WebsosoAuthSessionManager.kt
  app/src/main/java/com/into/websoso/data/authenticator/WebsosoAuthenticator.kt
  app/src/main/java/com/into/websoso/data/di/ApiModule.kt
  app/src/main/java/com/into/websoso/data/di/NetworkModule.kt
  app/src/main/java/com/into/websoso/data/di/OAuthModule.kt
  app/src/main/java/com/into/websoso/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/into/websoso/data/mapper/KakaoTokenMapper.kt
  app/src/main/java/com/into/websoso/data/mapper/LoginMapper.kt
  app/src/main/java/com/into/websoso/data/model/LoginEntity.kt
  app/src/main/java/com/into/websoso/data/model/OAuthToken.kt
  app/src/main/java/com/into/websoso/data/qualifier/Auth.kt
  app/src/main/java/com/into/websoso/data/qualifier/Interceptor.kt
  app/src/main/java/com/into/websoso/data/remote/api/AuthApi.kt
  app/src/main/java/com/into/websoso/data/remote/api/KakaoAuthService.kt
  app/src/main/java/com/into/websoso/data/remote/api/OAuthService.kt
  app/src/main/java/com/into/websoso/data/remote/request/TokenReissueRequestDto.kt
  app/src/main/java/com/into/websoso/data/remote/response/KakaoLoginResponseDto.kt
  app/src/main/java/com/into/websoso/data/repository/AuthRepository.kt
  app/src/main/java/com/into/websoso/ui/login/LoginActivity.kt
  app/src/main/java/com/into/websoso/ui/login/LoginViewModel.kt
  app/src/main/java/com/into/websoso/ui/login/model/LoginUiState.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/onboarding/OnboardingActivity.kt
  app/src/main/res/drawable/bg_login_white_radius_14dp_stroke_primary100_1dp.xml
  app/src/main/res/layout/activity_login.xml
  core/auth/build.gradle.kts
  core/auth/src/main/java/com/into/websoso/core/auth/AuthSessionManager.kt
  core/common/src/main/java/com/into/websoso/core/common/dispatchers/DispatchersModule.kt
  core/common/src/main/java/com/into/websoso/core/common/extensions/ThrottleHelper.kt
  core/common/src/main/java/com/into/websoso/core/common/navigator/NavigatorProvider.kt
  core/datastore/build.gradle.kts
  core/datastore/src/main/java/com/into/websoso/core/datastore/datasource/account/DefaultAccountDataSource.kt
  core/datastore/src/main/java/com/into/websoso/core/datastore/datasource/gitkeep
  core/datastore/src/main/java/com/into/websoso/core/datastore/di/DataStoreModule.kt
  core/datastore/src/main/java/com/into/websoso/core/datastore/di/DataStoreQualifier.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/into/websoso/core/network/authenticator/AuthorizationAuthenticator.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/AccountApi.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/AccountDataSourceModule.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/DefaultAccountDataSource.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/model/KakaoLoginResponseDto.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/model/TokenReissueRequestDto.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/model/TokenReissueResponseDto.kt
  core/network/src/main/java/com/into/websoso/core/network/di/NetworkModule.kt
  core/network/src/main/java/com/into/websoso/core/network/interceptor/AuthorizationInterceptor.kt
  data/account/src/main/java/com/into/websoso/data/account/AccountEntity.kt
  data/account/src/main/java/com/into/websoso/data/account/AccountRepository.kt
  data/account/src/main/java/com/into/websoso/data/account/datasource/AccountLocalDataSource.kt
  data/account/src/main/java/com/into/websoso/data/account/datasource/AccountRemoteDataSource.kt
  data/account/src/main/java/com/into/websoso/data/account/model/AccountEntity.kt
  data/account/src/main/java/com/into/websoso/data/account/model/TokenEntity.kt
  feature/signin/src/main/java/com/into/websoso/feature/signin/SignInScreen.kt
  feature/signin/src/main/java/com/into/websoso/feature/signin/SignInViewModel.kt
Labels: 🍯 [FEAT], ♻️ [REFACTOR], ⚖️ 재상 세훈

#686 refactor: 자동로그인 로직 구현
  app/build.gradle.kts
  app/src/main/java/com/into/websoso/ui/splash/SplashActivity.kt
  app/src/main/java/com/into/websoso/ui/splash/SplashViewModel.kt
  app/src/main/java/com/into/websoso/ui/splash/dialog/MinimumVersionDialogFragment.kt
  core/datastore/src/main/java/com/into/websoso/core/datastore/datasource/account/DefaultAccountDataSource.kt
  data/account/src/main/java/com/into/websoso/data/account/AccountRepository.kt
  data/account/src/main/java/com/into/websoso/data/account/datasource/AccountLocalDataSource.kt
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈

#689 refactor: 회원탈퇴 구현
  app/src/main/java/com/into/websoso/data/remote/api/AuthApi.kt
  app/src/main/java/com/into/websoso/data/repository/AuthRepository.kt
  app/src/main/java/com/into/websoso/ui/withdraw/second/WithdrawSecondActivity.kt
  app/src/main/java/com/into/websoso/ui/withdraw/second/WithdrawSecondViewModel.kt
  core/auth-kakao/src/main/java/com/into/websoso/core/auth_kakao/KakaoAuthClient.kt
  core/auth/src/main/java/com/into/websoso/core/auth/AuthClient.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/AccountApi.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/DefaultAccountDataSource.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/model/request/KakaoLogoutRequestDto.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/model/request/KakaoWithdrawRequestDto.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/model/request/TokenReissueRequestDto.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/model/response/KakaoLoginResponseDto.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/account/model/response/TokenReissueResponseDto.kt
  data/account/src/main/java/com/into/websoso/data/account/AccountRepository.kt
  data/account/src/main/java/com/into/websoso/data/account/datasource/AccountRemoteDataSource.kt
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈

#691 refactor: 회원가입 로직 수정
  app/src/main/java/com/into/websoso/WebsosoApp.kt
  app/src/main/java/com/into/websoso/core/common/util/navigator/WebsosoNavigator.kt
  app/src/main/java/com/into/websoso/data/di/RepositoryModule.kt
  app/src/main/java/com/into/websoso/data/remote/api/AuthApi.kt
  app/src/main/java/com/into/websoso/data/repository/AuthRepository.kt
  app/src/main/java/com/into/websoso/ui/accountInfo/LogoutDialogFragment.kt
  app/src/main/java/com/into/websoso/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/into/websoso/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/into/websoso/ui/splash/SplashActivity.kt
  app/src/main/java/com/into/websoso/ui/withdraw/second/WithdrawSecondActivity.kt
  core/common/src/main/java/com/into/websoso/core/common/navigator/NavigatorProvider.kt
  feature/signin/src/main/java/com/into/websoso/feature/signin/SignInScreen.kt
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈

#695 feat: 서재 UI/UX 개편 (1) - 레이어 모듈 분리
  core/network/build.gradle.kts
  core/network/src/main/java/com/into/websoso/core/network/datasource/library/DefaultLibraryDataSource.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/library/LibraryApi.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/library/model/response/NovelResponseDto.kt
  core/network/src/main/java/com/into/websoso/core/network/datasource/library/model/response/UserLibraryResponseDto.kt
  data/library/.gitignore
  data/library/build.gradle.kts
  data/library/consumer-rules.pro
  data/library/proguard-rules.pro
  data/library/src/main/AndroidManifest.xml
  data/library/src/main/java/com/into/websoso/data/library/LibraryRepository.kt
  data/library/src/main/java/com/into/websoso/data/library/datasource/LibraryLocalDataSource.kt
  data/library/src/main/java/com/into/websoso/data/library/datasource/LibraryRemoteDataSource.kt
  feature/library/.gitignore
  feature/library/build.gradle.kts
  feature/library/consumer-rules.pro
  feature/library/proguard-rules.pro
  feature/library/src/main/AndroidManifest.xml
  settings.gradle.kts
Labels: ⚖️ 재상 세훈, 🚧 [BUILD]

#697 feat: 서재 UI/UX 개편 (3) - Room 모듈 구현
  app/src/main/java/com/into/websoso/ui/splash/SplashViewModel.kt
  core/database/.gitignore
  core/database/build.gradle.kts
  core/database/consumer-rules.pro
  core/database/proguard-rules.pro
  core/database/src/main/AndroidManifest.xml
  core/database/src/main/java/com/into/websoso/core/database/WebsosoDatabase.kt
  core/database/src/main/java/com/into/websoso/core/database/datasource/library/DefaultLibraryDataSource.kt
  core/database/src/main/java/com/into/websoso/core/database/datasource/library/NovelDao.kt
  core/database/src/main/java/com/into/websoso/core/database/di/DatabaseModule.kt
  core/database/src/main/java/com/into/websoso/core/database/entity/NovelEntity.kt
  core/datastore/src/main/java/com/into/websoso/core/datastore/datasource/account/DefaultAccountDataSource.kt
  core/network/src/main/java/com/into/websoso/core/network/authenticator/AuthorizationAuthenticator.kt
  data/account/src/main/java/com/into/websoso/data/account/AccountRepository.kt
  data/account/src/main/java/com/into/websoso/data/account/datasource/AccountLocalDataSource.kt
  data/library/src/main/java/com/into/websoso/data/library/datasource/LibraryLocalDataSource.kt
  feature/signin/src/main/java/com/into/websoso/feature/signin/SignInViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🍯 [FEAT], ⚖️ 재상 세훈, 🚧 [BUILD]

#703 feat: 서재UI/UX 개편 (1) : 서재모듈 구현
  feature/library/src/main/java/com/into/websoso/feature/library/LibraryViewModel.kt
  feature/signin/src/main/java/com/into/websoso/feature/signin/SignInScreen.kt
Labels: 👛 황후 연진, 🚧 [BUILD]

#707 feat: 피드 생성 이미지 컨테이너 UI 구현
  app/src/main/java/com/into/websoso/ui/createFeed/component/CreateFeedImageContainer.kt
  app/src/main/res/layout/activity_create_feed.xml
  core/resource/src/main/res/drawable/ic_feed_remove_image.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#670 refactor: 피드 비공개 반영 관련 세부 디테일 수정
  app/src/main/java/com/into/websoso/ui/createFeed/component/CreateFeedImageContainer.kt
  app/src/main/res/layout/activity_create_feed.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_feed_detail_header.xml
  app/src/main/res/layout/item_my_activity.xml
  core/resource/src/main/res/drawable/ic_feed_remove_image.xml
  core/resource/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], 🔮 법사 준서

#685 feat: 피드 상세 이미지 컨테이너 UI 구현
  app/src/main/java/com/into/websoso/ui/createFeed/component/CreateFeedImageContainer.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/FeedDetailClickListener.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/adapter/FeedDetailContentViewHolder.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/component/AdaptationFeedImageContainer.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/component/DoubleImageContainer.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/component/MultipleImageContainer.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/component/SingleImageContainer.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/component/TripleImageContainer.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/model/ImageContainerType.kt
  app/src/main/res/drawable/bg_feed_gray_toast_radius_24dp.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_feed_detail_header.xml
Labels: 🍯 [FEAT], 🔮 법사 준서
