Repository Team-WSS/WSS-Android, pull requests merged in 2025-03, with the labels that each got.

#599 release: 1.1.0 업데이트(to develop)
  app/src/main/java/com/into/websoso/core/common/util/ExtentionFuction.kt
  app/src/main/java/com/into/websoso/core/designsystem/theme/Theme.kt
  app/src/main/java/com/into/websoso/data/model/NotificationEntity.kt
  app/src/main/java/com/into/websoso/data/repository/NotificationRepository.kt
  app/src/main/java/com/into/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/into/websoso/domain/mapper/NotificationMapper.kt
  app/src/main/java/com/into/websoso/domain/model/Notification.kt
  app/src/main/java/com/into/websoso/domain/usecase/GetNotificationListUseCase.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/into/websoso/ui/main/home/dialog/TermsAgreementDialogFragment.kt
  app/src/main/java/com/into/websoso/ui/mapper/NotificationMapper.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationActivity.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationScreen.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationViewModel.kt
  app/src/main/java/com/into/websoso/ui/notification/component/NotificationAppBar.kt
  app/src/main/java/com/into/websoso/ui/notification/component/NotificationCard.kt
  app/src/main/java/com/into/websoso/ui/notification/component/NotificationsContainer.kt
  app/src/main/java/com/into/websoso/ui/notification/model/NotificationUIModel.kt
  app/src/main/java/com/into/websoso/ui/notification/model/NotificationUIState.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/NotificationDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/NotificationDetailScreen.kt
  app/src/main/java/com/into/websoso/ui/termsAgreement/TermsAgreementDialogBottomSheet.kt
  app/src/main/java/com/into/websoso/ui/withdraw/second/WithdrawSecondActivity.kt
  app/src/main/java/com/into/websoso/ui/withdraw/second/WithdrawSecondViewModel.kt
  app/src/main/res/layout/dialog_terms_agreement.xml
  app/src/main/res/values/deepLinks.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🚀 [RELEASE]

#610 fix: 피드 디테일에서 뒤로 갔을 때 위치 수정
  app/src/main/java/com/into/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/into/websoso/ui/main/feed/FeedViewModel.kt
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈, 🔨 [FIX]

#607 fix: 프로필 설명 글이 짤린 현상
  app/src/main/res/layout/activity_other_user_page.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: 🏹 궁사 명지, 🔨 [FIX]

#616 fix: 보관함 작품 취향 / 장르 취향 반영 안 되는 이슈
  app/src/main/java/com/into/websoso/ui/userStorage/UserStorageActivity.kt
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈, 🔨 [FIX]

#615 fix: ‘작성완료!’ 토스트 노출 버그
  app/src/main/java/com/into/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/main/feed/FeedFragment.kt
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈, 🔨 [FIX]

#621 release: 1.1.1 버전 업데이트(to master)
  app/src/main/java/com/into/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/main/feed/FeedFragment.kt
  app/src/main/java/com/into/websoso/ui/main/feed/FeedViewModel.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/into/websoso/ui/main/home/dialog/TermsAgreementDialogFragment.kt
  app/src/main/java/com/into/websoso/ui/userStorage/UserStorageActivity.kt
  app/src/main/res/layout/activity_other_user_page.xml
  app/src/main/res/layout/fragment_my_page.xml
  gradle/libs.versions.toml
Labels: 🚀 [RELEASE]

#620 release: 1.1.1 버전 업데이트(to develop)
  gradle/libs.versions.toml
Labels: 🏹 궁사 명지, 🚀 [RELEASE]
