Repository Team-WSS/WSS-Android, pull requests merged in 2025-02, with the labels that each got.

#570 feat: 리드미 업데이트
  README.md
Labels: 🍯 [FEAT], 🏹 궁사 명지

#575 fix: 푸시 알림 클릭 시 읽음 처리 되지 않는 현상 해결
  app/src/main/java/com/into/websoso/core/common/util/message/WSSFirebaseMessagingService.kt
Labels: 🏹 궁사 명지, 🔨 [FIX]

#577 feat: 약관동의 바텀시트 및 팝업 UI 구현
  app/src/main/java/com/into/websoso/core/common/util/ExtentionFuction.kt
  app/src/main/java/com/into/websoso/core/common/util/message/WSSFirebaseMessagingService.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/dialog/TermsAgreementDialogFragment.kt
  app/src/main/java/com/into/websoso/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/into/websoso/ui/termsAgreement/TermsAgreementDialogBottomSheet.kt
  app/src/main/java/com/into/websoso/ui/termsAgreement/TermsAgreementViewModel.kt
  app/src/main/java/com/into/websoso/ui/termsAgreement/model/AgreementType.kt
  app/src/main/res/drawable/ic_terms_agreement_selected.xml
  app/src/main/res/drawable/ic_terms_agreement_unselected.xml
  app/src/main/res/layout/dialog_terms_agreement.xml
  app/src/main/res/layout/dialog_terms_agreement_popup_menu.xml
  app/src/main/res/values/deepLinks.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#576 fix: 알림 모두 읽었는데 홈 화면 아이콘 점 사라지지 않는 이슈
  app/src/main/java/com/into/websoso/core/common/ui/model/ResultFrom.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationActivity.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationScreen.kt
  app/src/main/res/layout/fragment_home.xml
Labels: 🔨 [FIX], 🔮 법사 준서

#580 feat: 약관동의 api 연결
  app/src/main/java/com/into/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/into/websoso/data/model/TermsAgreementEntity.kt
  app/src/main/java/com/into/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/into/websoso/data/remote/request/TermsAgreementRequestDto.kt
  app/src/main/java/com/into/websoso/data/remote/response/TermsAgreementResponseDto.kt
  app/src/main/java/com/into/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/into/websoso/ui/termsAgreement/TermsAgreementDialogBottomSheet.kt
  app/src/main/java/com/into/websoso/ui/termsAgreement/TermsAgreementViewModel.kt
Labels: 🍯 [FEAT], 👛 황후 연진

#579 feat: 로그아웃 시 fcm 토큰 제거 로직 구현
  app/src/main/java/com/into/websoso/data/remote/api/AuthApi.kt
  app/src/main/java/com/into/websoso/data/remote/request/LogoutRequestDto.kt
  app/src/main/java/com/into/websoso/data/repository/AuthRepository.kt
  app/src/main/java/com/into/websoso/data/repository/PushMessageRepository.kt
  app/src/main/java/com/into/websoso/ui/accountInfo/AccountInfoViewModel.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
Labels: 🍯 [FEAT], 🏹 궁사 명지

#581 feat: 약관동의 기능 구현
  app/src/main/java/com/into/websoso/core/common/util/ExtentionFuction.kt
  app/src/main/java/com/into/websoso/data/mapper/UserMapper.kt
  app/src/main/java/com/into/websoso/data/model/TermsAgreementEntity.kt
  app/src/main/java/com/into/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/into/websoso/data/remote/request/TermsAgreementRequestDto.kt
  app/src/main/java/com/into/websoso/data/remote/response/TermsAgreementResponseDto.kt
  app/src/main/java/com/into/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/into/websoso/ui/main/home/dialog/TermsAgreementDialogFragment.kt
  app/src/main/java/com/into/websoso/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/into/websoso/ui/termsAgreement/TermsAgreementDialogBottomSheet.kt
  app/src/main/java/com/into/websoso/ui/termsAgreement/TermsAgreementViewModel.kt
  app/src/main/java/com/into/websoso/ui/termsAgreement/model/AgreementType.kt
  app/src/main/res/drawable/ic_terms_agreement_selected.xml
  app/src/main/res/drawable/ic_terms_agreement_unselected.xml
  app/src/main/res/layout/dialog_terms_agreement.xml
  app/src/main/res/layout/dialog_terms_agreement_popup_menu.xml
  app/src/main/res/values/deepLinks.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#588 bugfix: 약관동의 다이얼로그 관련 qa 수정사항 반영
  app/src/main/java/com/into/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/dialog/TermsAgreementDialogFragment.kt
  app/src/main/java/com/into/websoso/ui/termsAgreement/TermsAgreementDialogBottomSheet.kt
  app/src/main/java/com/into/websoso/ui/withdraw/second/WithdrawSecondViewModel.kt
  app/src/main/res/layout/dialog_terms_agreement.xml
  app/src/main/res/values/deepLinks.xml
  app/src/main/res/values/strings.xml
Labels: 👛 황후 연진, 🔨 [FIX]

#590 bugfix: 약관동의 다이얼로그 관련 qa 사항 수정
  app/src/main/java/com/into/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/dialog/TermsAgreementDialogFragment.kt
  app/src/main/java/com/into/websoso/ui/termsAgreement/TermsAgreementDialogBottomSheet.kt
  app/src/main/java/com/into/websoso/ui/withdraw/second/WithdrawSecondViewModel.kt
  app/src/main/res/layout/dialog_terms_agreement.xml
  app/src/main/res/values/deepLinks.xml
  app/src/main/res/values/strings.xml
Labels: 👛 황후 연진, 🔨 [FIX]

#589 bugfix: 알림 뷰 제목의 줄바꿈 제거
  app/src/main/java/com/into/websoso/data/model/NotificationEntity.kt
  app/src/main/java/com/into/websoso/data/repository/NotificationRepository.kt
  app/src/main/java/com/into/websoso/domain/mapper/NotificationMapper.kt
  app/src/main/java/com/into/websoso/domain/model/Notification.kt
  app/src/main/java/com/into/websoso/domain/usecase/GetNotificationListUseCase.kt
  app/src/main/java/com/into/websoso/ui/mapper/NotificationMapper.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationActivity.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationScreen.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationViewModel.kt
  app/src/main/java/com/into/websoso/ui/notification/component/NotificationCard.kt
  app/src/main/java/com/into/websoso/ui/notification/component/NotificationsContainer.kt
  app/src/main/java/com/into/websoso/ui/notification/model/NotificationUIModel.kt
  app/src/main/java/com/into/websoso/ui/notification/model/NotificationUIState.kt
Labels: 🔨 [FIX], 🔮 법사 준서

#593 bugfix: 컴포즈 뷰 다크모드 상단바 디자인 수정
  app/src/main/java/com/into/websoso/core/common/util/ExtentionFuction.kt
  app/src/main/java/com/into/websoso/core/designsystem/theme/Theme.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationActivity.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationScreen.kt
  app/src/main/java/com/into/websoso/ui/notification/component/NotificationAppBar.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/NotificationDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/NotificationDetailScreen.kt
Labels: 🔨 [FIX], 🔮 법사 준서

#594 bugfix: 약관동의 다이얼로그 관련 이슈 수정
  app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/res/layout/dialog_terms_agreement.xml
Labels: 👛 황후 연진, 🔨 [FIX]

#595 bugfix: 홈 화면 알림 읽어야 하는 아이콘 뜨지 않는 이슈
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
Labels: ⚖️ 재상 세훈, 🏹 궁사 명지, 👛 황후 연진, 🔨 [FIX], 🔮 법사 준서

#597 bugfix: 약관동의 확인 다이얼로그 외부터치 금지 구현
  app/src/main/java/com/into/websoso/ui/main/home/dialog/TermsAgreementDialogFragment.kt
Labels: 👛 황후 연진, 🔨 [FIX]
