Repository Team-WSS/WSS-Android, pull requests merged in 2025-08, with the labels that each got.

#735 feat: 서재UI/UX 개편 (14) - Room 동기화 및 최적화
  app/src/main/java/com/into/websoso/data/di/RepositoryModule.kt
  app/src/main/java/com/into/websoso/data/model/NovelRatingEntity.kt
  app/src/main/java/com/into/websoso/data/repository/FeedRepository.kt
  app/src/main/java/com/into/websoso/data/repository/NovelRepository.kt
  app/src/main/java/com/into/websoso/data/repository/UserNovelRepository.kt
  app/src/main/java/com/into/websoso/ui/accountInfo/AccountInfoActivity.kt
  app/src/main/java/com/into/websoso/ui/accountInfo/AccountInfoViewModel.kt
  app/src/main/java/com/into/websoso/ui/activityDetail/ActivityDetailViewModel.kt
  app/src/main/java/com/into/websoso/ui/createFeed/CreateFeedActivity.kt
  app/src/main/java/com/into/websoso/ui/createFeed/CreateFeedViewModel.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/FeedDetailViewModel.kt
  app/src/main/java/com/into/websoso/ui/main/feed/FeedViewModel.kt
  app/src/main/java/com/into/websoso/ui/main/library/LibraryFragment.kt
  app/src/main/java/com/into/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
  app/src/main/java/com/into/websoso/ui/novelDetail/NovelDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/novelDetail/model/NovelDetailModel.kt
  app/src/main/java/com/into/websoso/ui/novelFeed/NovelFeedViewModel.kt
  app/src/main/java/com/into/websoso/ui/novelRating/NovelRatingActivity.kt
  app/src/main/java/com/into/websoso/ui/novelRating/NovelRatingViewModel.kt
  app/src/main/java/com/into/websoso/ui/withdraw/second/WithdrawSecondViewModel.kt
  app/src/main/res/layout/activity_account_info.xml
  core/database/src/main/java/com/into/websoso/core/database/datasource/library/DefaultLibraryLocalDataSource.kt
  core/database/src/main/java/com/into/websoso/core/database/datasource/library/dao/NovelDao.kt
  core/database/src/main/java/com/into/websoso/core/database/datasource/library/entity/InDatabaseNovelEntity.kt
  core/database/src/main/java/com/into/websoso/core/database/datasource/library/mapper/NovelMapper.kt
  core/database/src/main/java/com/into/websoso/core/database/datasource/library/paging/MapValuePagingSource.kt
  data/library/src/main/java/com/into/websoso/data/filter/repository/MyLibraryFilterRepository.kt
  data/library/src/main/java/com/into/websoso/data/library/LibraryRepository.kt
  data/library/src/main/java/com/into/websoso/data/library/datasource/LibraryLocalDataSource.kt
  data/library/src/main/java/com/into/websoso/data/library/paging/LibraryRemoteMediator.kt
  data/library/src/main/java/com/into/websoso/data/library/repository/MyLibraryRepository.kt
  feature/library/src/main/java/com/into/websoso/feature/library/LibraryScreen.kt
  feature/library/src/main/java/com/into/websoso/feature/library/LibraryViewModel.kt
  feature/library/src/main/java/com/into/websoso/feature/library/model/NovelUiModel.kt
  feature/library/src/main/java/com/into/websoso/feature/library/model/RatingStarUiModel.kt
  feature/library/src/main/java/com/into/websoso/feature/library/model/ReadStatusUiModel.kt
Labels: 🍯 [FEAT], ⚖️ 재상 세훈

#739 feat: targetSdk35 로 수정
  app/build.gradle.kts
  build-logic/src/main/kotlin/websoso.android.kotlin.gradle.kts
  core/resource/build.gradle.kts
Labels: 🍯 [FEAT], 🏹 궁사 명지

#741 feat: android 35 이상 edgeToEdge 대응
  app/src/main/java/com/into/websoso/core/common/ui/base/BaseActivity.kt
  app/src/main/java/com/into/websoso/ui/main/MainActivity.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationActivity.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationScreen.kt
  app/src/main/res/layout/activity_main.xml
  feature/library/src/main/java/com/into/websoso/feature/library/LibraryScreen.kt
Labels: 🍯 [FEAT], 🏹 궁사 명지

#743 fix: 서재소소 최종 QA 사항 반영
  app/src/main/java/com/into/websoso/ui/novelRating/NovelRatingViewModel.kt
  domain/library/src/main/java/com/into/websoso/domain/library/model/ReadStatus.kt
  feature/library/src/main/java/com/into/websoso/feature/library/component/LibraryFilterEmptyView.kt
  feature/library/src/main/java/com/into/websoso/feature/library/component/LibraryGridListItem.kt
  feature/library/src/main/java/com/into/websoso/feature/library/component/LibrayFilterTopBar.kt
Labels: ♻️ [REFACTOR], ⚖️ 재상 세훈, 🔨 [FIX]

#747 fix: 서재 작품 전체 별점 0.0 으로 보이는 이슈 해결
  domain/library/src/main/java/com/into/websoso/domain/library/model/Rating.kt
  feature/library/src/main/java/com/into/websoso/feature/library/component/LibraryListItem.kt
  feature/library/src/main/java/com/into/websoso/feature/library/mapper/NovelMapper.kt
  feature/library/src/main/java/com/into/websoso/feature/library/model/NovelUiModel.kt
Labels: 🏹 궁사 명지, 🔨 [FIX]
