Repository Team-WSS/WSS-Android, pull requests merged in 2025-01, with the labels that each got.

#507 fix: 1.0.6 배포 url 수정
  app/build.gradle.kts
Labels: ⚖️ 재상 세훈, 🏹 궁사 명지, 🔨 [FIX], 🚧 [BUILD], 🚨[Emergency]

#508 fix: 1.0.6 배포 url 수정
  app/build.gradle.kts
  app/src/main/java/com/into/websoso/ui/main/feed/FeedFragment.kt
Labels: 🏹 궁사 명지, 🔨 [FIX], 🚧 [BUILD], 🚨[Emergency]

#512 fix: 이벤트 트래커 DI 주입을 위한 다이얼로그 바텀시트 AndroidEntryPoint 추가
  app/build.gradle.kts
  app/src/main/java/com/into/websoso/ui/createFeed/CreateFeedSearchNovelBottomSheetDialog.kt
  app/src/main/java/com/into/websoso/ui/main/feed/dialog/FeedReportDialogFragment.kt
Labels: 🏹 궁사 명지, 🔨 [FIX], 🚨[Emergency]

#514 hotfix: 이벤트 트래커 DI 주입을 위한 다이얼로그 바텀시트 AndroidEntryPoint 추가
  app/build.gradle.kts
  app/src/main/java/com/into/websoso/ui/createFeed/CreateFeedSearchNovelBottomSheetDialog.kt
  app/src/main/java/com/into/websoso/ui/main/feed/dialog/FeedReportDialogFragment.kt
Labels: ⚖️ 재상 세훈, 🔨 [FIX]

#510 refactor: 빌드 옵션에 따른 도메인 분리
  .github/workflows/WSS_PR_builder.yml
  app/build.gradle.kts
Labels: ♻️ [REFACTOR], 🏹 궁사 명지, 🔮 법사 준서, 🚧 [BUILD]

#525 refactort: 홈 디자인 QA
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/typography.xml
Labels: ♻️ [REFACTOR], 🗡️ 대장군 재원

#548 feat: Notice 뷰 UI 수정 사항 반영
  app/src/main/java/com/into/websoso/common/ui/component/AdaptationImage.kt
  app/src/main/java/com/into/websoso/common/ui/component/ExternalImage.kt
  app/src/main/java/com/into/websoso/designsystem/theme/Color.kt
  app/src/main/java/com/into/websoso/designsystem/theme/Theme.kt
  app/src/main/java/com/into/websoso/designsystem/theme/Type.kt
  app/src/main/java/com/into/websoso/domain/mapper/NoticeMapper.kt
  app/src/main/java/com/into/websoso/ui/notice/NoticeActivity.kt
  app/src/main/java/com/into/websoso/ui/notice/NoticeScreen.kt
  app/src/main/java/com/into/websoso/ui/notice/NoticeViewModel.kt
  app/src/main/java/com/into/websoso/ui/notice/component/NoticeAppBar.kt
  app/src/main/java/com/into/websoso/ui/notice/component/NoticeCard.kt
  app/src/main/java/com/into/websoso/ui/notice/component/NoticesContainer.kt
  app/src/main/java/com/into/websoso/ui/notice/model/NoticeUiState.kt
  app/src/main/java/com/into/websoso/ui/noticeDetail/NoticeDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/novelInfo/component/NovelInfoPlatformsContainer.kt
  app/src/main/java/com/into/websoso/ui/novelInfo/component/PlatformCard.kt
  lint.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#546 feat: Notice 뷰 API 수정 사항 반영
  app/build.gradle.kts
  app/src/main/java/com/into/websoso/common/ui/component/AdaptationImage.kt
  app/src/main/java/com/into/websoso/common/ui/component/ExternalImage.kt
  app/src/main/java/com/into/websoso/data/mapper/NoticeMapper.kt
  app/src/main/java/com/into/websoso/data/model/NoticesEntity.kt
  app/src/main/java/com/into/websoso/data/model/NotificationEntity.kt
  app/src/main/java/com/into/websoso/data/model/NotificationsEntity.kt
  app/src/main/java/com/into/websoso/data/remote/api/NoticeApi.kt
  app/src/main/java/com/into/websoso/data/remote/response/NoticesResponseDto.kt
  app/src/main/java/com/into/websoso/data/remote/response/NotificationsResponseDto.kt
  app/src/main/java/com/into/websoso/data/repository/NoticeRepository.kt
  app/src/main/java/com/into/websoso/designsystem/theme/Color.kt
  app/src/main/java/com/into/websoso/designsystem/theme/Theme.kt
  app/src/main/java/com/into/websoso/designsystem/theme/Type.kt
  app/src/main/java/com/into/websoso/domain/mapper/NoticeMapper.kt
  app/src/main/java/com/into/websoso/domain/model/Notice.kt
  app/src/main/java/com/into/websoso/domain/model/NoticeInfo.kt
  app/src/main/java/com/into/websoso/domain/model/NoticeType.kt
  app/src/main/java/com/into/websoso/domain/usecase/GetNoticeListUseCase.kt
  app/src/main/java/com/into/websoso/ui/mapper/NoticeMapper.kt
  app/src/main/java/com/into/websoso/ui/notice/NoticeActivity.kt
  app/src/main/java/com/into/websoso/ui/notice/NoticeScreen.kt
  app/src/main/java/com/into/websoso/ui/notice/NoticeViewModel.kt
  app/src/main/java/com/into/websoso/ui/notice/adapter/NoticeAdapter.kt
  app/src/main/java/com/into/websoso/ui/notice/adapter/NoticeViewHolder.kt
  app/src/main/java/com/into/websoso/ui/notice/component/NoticeAppBar.kt
  app/src/main/java/com/into/websoso/ui/notice/component/NoticeCard.kt
  app/src/main/java/com/into/websoso/ui/notice/component/NoticesContainer.kt
  app/src/main/java/com/into/websoso/ui/notice/model/NoticeModel.kt
  app/src/main/java/com/into/websoso/ui/notice/model/NoticeUiState.kt
  app/src/main/java/com/into/websoso/ui/noticeDetail/NoticeDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/novelInfo/component/NovelInfoPlatformsContainer.kt
  app/src/main/java/com/into/websoso/ui/novelInfo/component/PlatformCard.kt
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_notice_detail.xml
  app/src/main/res/layout/item_notice.xml
  gradle/libs.versions.toml
  lint.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#553 build: 배포 버전, 디버그 버전 빌드 분리
  app/build.gradle.kts
  app/src/debug/ic_wss_logo_debug-playstore.png
  app/src/debug/res/drawable/ic_wss_logo_debug_foreground.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_wss_logo_debug.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_wss_logo_debug_round.xml
  app/src/debug/res/mipmap-hdpi/ic_wss_logo_debug.webp
  app/src/debug/res/mipmap-hdpi/ic_wss_logo_debug_foreground.webp
  app/src/debug/res/mipmap-hdpi/ic_wss_logo_debug_round.webp
  app/src/debug/res/mipmap-mdpi/ic_wss_logo_debug.webp
  app/src/debug/res/mipmap-mdpi/ic_wss_logo_debug_foreground.webp
  app/src/debug/res/mipmap-mdpi/ic_wss_logo_debug_round.webp
  app/src/debug/res/mipmap-xhdpi/ic_wss_logo_debug.webp
  app/src/debug/res/mipmap-xhdpi/ic_wss_logo_debug_foreground.webp
  app/src/debug/res/mipmap-xhdpi/ic_wss_logo_debug_round.webp
  app/src/debug/res/mipmap-xxhdpi/ic_wss_logo_debug.webp
  app/src/debug/res/mipmap-xxhdpi/ic_wss_logo_debug_foreground.webp
  app/src/debug/res/mipmap-xxhdpi/ic_wss_logo_debug_round.webp
  app/src/debug/res/mipmap-xxxhdpi/ic_wss_logo_debug.webp
  app/src/debug/res/mipmap-xxxhdpi/ic_wss_logo_debug_foreground.webp
  app/src/debug/res/mipmap-xxxhdpi/ic_wss_logo_debug_round.webp
  app/src/main/AndroidManifest.xml
  app/src/main/ic_wss_logo_debug-playstore.png
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], ⚖️ 재상 세훈, 🚧 [BUILD]

#556 feat: 알림 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/into/websoso/core/common/util/message/WSSFirebaseMessagingService.kt
  app/src/main/java/com/into/websoso/data/remote/api/AuthApi.kt
  app/src/main/java/com/into/websoso/data/remote/request/FCMTokenRequestDto.kt
  app/src/main/java/com/into/websoso/data/repository/AuthRepository.kt
  app/src/main/java/com/into/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
  gradle/libs.versions.toml
Labels: 🍯 [FEAT], 🏹 궁사 명지

#555 feat: 알림 단건 api 로 알림 상세 뷰 로직 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/into/websoso/core/designsystem/theme/Color.kt
  app/src/main/java/com/into/websoso/core/designsystem/theme/Type.kt
  app/src/main/java/com/into/websoso/data/mapper/NoticeMapper.kt
  app/src/main/java/com/into/websoso/data/model/NotificationDetailEntity.kt
  app/src/main/java/com/into/websoso/data/remote/api/NoticeApi.kt
  app/src/main/java/com/into/websoso/data/remote/response/NotificationDetailResponseDto.kt
  app/src/main/java/com/into/websoso/data/repository/NoticeRepository.kt
  app/src/main/java/com/into/websoso/ui/notice/NoticeActivity.kt
  app/src/main/java/com/into/websoso/ui/noticeDetail/NoticeDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/NotificationDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/NotificationDetailScreen.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/NotificationDetailViewModel.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/component/HyperlinkText.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/component/NotificationDetailContent.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/model/NotificationDetailUiState.kt
  app/src/main/res/layout/activity_notice_detail.xml
Labels: 🍯 [FEAT], 🗡️ 대장군 재원

#552 feat: 알림 읽음 여부에 따른 아이콘 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/into/websoso/data/di/ApiModule.kt
  app/src/main/java/com/into/websoso/data/mapper/NotificationMapper.kt
  app/src/main/java/com/into/websoso/data/model/NotificationEntity.kt
  app/src/main/java/com/into/websoso/data/remote/api/NotificationApi.kt
  app/src/main/java/com/into/websoso/data/remote/response/NotificationUnreadResponseDto.kt
  app/src/main/java/com/into/websoso/data/remote/response/NotificationsResponseDto.kt
  app/src/main/java/com/into/websoso/data/repository/NoticeRepository.kt
  app/src/main/java/com/into/websoso/data/repository/NotificationRepository.kt
  app/src/main/java/com/into/websoso/domain/mapper/NoticeMapper.kt
  app/src/main/java/com/into/websoso/domain/mapper/NotificationMapper.kt
  app/src/main/java/com/into/websoso/domain/model/Notice.kt
  app/src/main/java/com/into/websoso/domain/model/NoticeInfo.kt
  app/src/main/java/com/into/websoso/domain/model/Notification.kt
  app/src/main/java/com/into/websoso/domain/model/NotificationInfo.kt
  app/src/main/java/com/into/websoso/domain/model/NotificationType.kt
  app/src/main/java/com/into/websoso/domain/usecase/GetNotificationListUseCase.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/into/websoso/ui/main/home/model/HomeUiState.kt
  app/src/main/java/com/into/websoso/ui/notice/NoticeScreen.kt
  app/src/main/java/com/into/websoso/ui/notice/NoticeViewModel.kt
  app/src/main/java/com/into/websoso/ui/notice/component/NoticesContainer.kt
  app/src/main/java/com/into/websoso/ui/notice/model/NoticeUiState.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationActivity.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationScreen.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationViewModel.kt
  app/src/main/java/com/into/websoso/ui/notification/component/NotificationAppBar.kt
  app/src/main/java/com/into/websoso/ui/notification/component/NotificationCard.kt
  app/src/main/java/com/into/websoso/ui/notification/component/NotificationsContainer.kt
  app/src/main/java/com/into/websoso/ui/notification/model/NotificationUiState.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/NotificationDetailScreen.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/NotificationDetailViewModel.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/component/NotificationDetailContent.kt
  app/src/main/java/com/into/websoso/ui/notificationDetail/model/NotificationDetailUiState.kt
  app/src/main/res/drawable/ic_home_notification.xml
  app/src/main/res/drawable/ic_home_notification_read.xml
  app/src/main/res/drawable/ic_home_notification_selector.xml
  app/src/main/res/drawable/ic_home_notification_unread.xml
  app/src/main/res/drawable/ic_notification_back.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🔮 법사 준서

#563 hotfix: 토큰 401 에러 해결
  app/build.gradle.kts
  app/src/main/java/com/into/websoso/ui/splash/SplashActivity.kt
  app/src/main/java/com/into/websoso/ui/splash/SplashViewModel.kt
Labels: 🏹 궁사 명지, 🚨[Emergency], 🔥[Hotfix]

#564 hotfix: 토큰 401 에러 해결
  app/src/main/java/com/into/websoso/ui/splash/SplashActivity.kt
  app/src/main/java/com/into/websoso/ui/splash/SplashViewModel.kt
  gradle/libs.versions.toml
Labels: 🏹 궁사 명지, 🔥[Hotfix]

#559 feat: 피드 알림 읽음 처리 추가
  app/src/main/java/com/into/websoso/data/remote/api/NotificationApi.kt
  app/src/main/java/com/into/websoso/data/repository/NotificationRepository.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/FeedDetailActivity.kt
  app/src/main/java/com/into/websoso/ui/feedDetail/FeedDetailViewModel.kt
  app/src/main/java/com/into/websoso/ui/notification/NotificationActivity.kt
Labels: 🍯 [FEAT], 🔮 법사 준서

#561 feat: 보관함 읽기 상태에 따른 탭 이동 구현
  app/src/main/java/com/into/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
  app/src/main/java/com/into/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
  app/src/main/java/com/into/websoso/ui/userStorage/UserStorageActivity.kt
  app/src/main/java/com/into/websoso/ui/userStorage/UserStorageViewModel.kt
  app/src/main/res/layout/fragment_my_library.xml
  app/src/main/res/layout/fragment_other_user_library.xml
Labels: 🍯 [FEAT], 👛 황후 연진

#566 feat: 알림 설정 로직 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/into/websoso/core/common/util/message/WSSFirebaseMessagingService.kt
  app/src/main/java/com/into/websoso/data/di/ApiModule.kt
  app/src/main/java/com/into/websoso/data/di/RepositoryModule.kt
  app/src/main/java/com/into/websoso/data/remote/api/PushMessageApi.kt
  app/src/main/java/com/into/websoso/data/remote/api/UserApi.kt
  app/src/main/java/com/into/websoso/data/remote/request/FCMTokenRequestDto.kt
  app/src/main/java/com/into/websoso/data/remote/request/NotificationPushEnabledRequestDto.kt
  app/src/main/java/com/into/websoso/data/remote/response/NotificationPushEnabledResponseDto.kt
  app/src/main/java/com/into/websoso/data/repository/AuthRepository.kt
  app/src/main/java/com/into/websoso/data/repository/PushMessageRepository.kt
  app/src/main/java/com/into/websoso/data/repository/UserFeedRepository.kt
  app/src/main/java/com/into/websoso/data/repository/UserRepository.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
  app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/into/websoso/ui/notificationSetting/NotificationSettingActivity.kt
  app/src/main/java/com/into/websoso/ui/notificationSetting/NotificationSettingViewModel.kt
  app/src/main/java/com/into/websoso/ui/setting/SettingActivity.kt
  app/src/main/java/com/into/websoso/ui/setting/SettingClickListener.kt
  app/src/main/java/com/into/websoso/ui/setting/dialog/NotificationPermissionDialog.kt
  app/src/main/java/com/into/websoso/ui/splash/SplashActivity.kt
  app/src/main/java/com/into/websoso/ui/splash/SplashViewModel.kt
  app/src/main/res/drawable/bg_notification_setting_off.xml
  app/src/main/res/drawable/bg_notification_setting_toggle.xml
  app/src/main/res/drawable/bg_notification_setting_toggle_on.xml
  app/src/main/res/drawable/bg_notification_setting_toggle_thumb.xml
  app/src/main/res/layout/activity_notification_setting.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/dialog_notification_permission.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 [FEAT], 🏹 궁사 명지
